denoland/deno_lint

- src/main.rs
- src/rules/mod.rs
- src/rules/no_dupe_keys.rs
Implementation of the [no-dupe-keys](https://eslint.org/docs/rules/no-dupe-keys) rule as per #1.
> Adding no-dupe-keys Rule

- README.md
- src/main.rs
- src/rules/eqeqeq.rs
- src/rules/mod.rs
This rule will check `==` and `!=`, but there are exceptions: when comparing with `null`, these operators are allowed.
> add eqeqeq rule

- src/main.rs
- src/rules/mod.rs
- src/rules/no_compare_neg_zero.rs
Adds [no-compare-neg-zero](https://eslint.org/docs/rules/no-compare-neg-zero) rule as per #1.
> Adding no-compare-neg-zero Rule

- src/main.rs
- src/rules/mod.rs
- src/rules/no_unsafe_finally.rs
Adds [no-unsafe-finally](https://eslint.org/docs/rules/no-unsafe-finally) as per #1.
> Adding no-unsafe-finally Rule

- README.md
- src/main.rs
- src/rules/default_param_last.rs
- src/rules/mod.rs
Ref: https://eslint.org/docs/rules/default-param-last
> add "default-param-last" rule

- README.md
- src/main.rs
- src/rules/mod.rs
- src/rules/no_new_symbol.rs
Ref: https://eslint.org/docs/rules/no-new-symbol
> add "no-new-symbol" rule

- README.md
- src/main.rs
- src/rules/mod.rs
- src/rules/no_throw_literal.rs
Ref: https://eslint.org/docs/rules/no-throw-literal
> add "no-throw-literal" rule

- .github/workflows/ci.yml
Closes https://github.com/denoland/deno_lint/issues/40
> add caching to CI

- README.md
- src/main.rs
- src/rules/mod.rs
- src/rules/no_cond_assign.rs
Adds [no-cond-assign](https://eslint.org/docs/rules/no-cond-assign) as per #1.
> Adds no-cond-assign Rule

- README.md
- src/main.rs
- src/rules/mod.rs
- src/rules/no_empty.rs
Adds [no-empty](https://eslint.org/docs/rules/no-empty) as per #1.
> Adds no-empty Rule

- Cargo.lock
- Cargo.toml
- src/linter.rs
- src/main.rs
- src/report_util.rs
- src/rules/mod.rs
- src/test_util.rs
fixes #47 
new result : 
```
problem.ts =>
1| var varName = "var value";
^
(noVar) `var` keyword is not allowed
18| debugger;
^
(noDebugger) `debugger` statement is not allowed
problem2.ts =>
1| const sparse = [1,,3];
^
(noSparseArray) Sparse arrays are not allowed
Found 3 problems
```
> show code snippets

- Cargo.lock
- Cargo.toml
- src/main.rs
> add clap CLI parser

- src/rules/mod.rs
- src/rules/no_obj_call.rs
+ `no obj call rule`
+ `12 tests about it`
> add no_obj_call rule

- src/rules/mod.rs
- src/rules/no_empty_character_class.rs
+ `no empty character class rule`
+ `3 tests about it`
> add no_empty_character_class rule

- .github/workflows/ci.yml
- src/main.rs
> ci: add build step, use release, fix config

- Cargo.toml
- src/lib.rs
- src/main.rs
- src/swc_util.rs
Even if the api is not currently stable it could be helpful to provide third party access to this crate.
> feat: add lib.rs

- src/main.rs
> Fix deno_lint --version

- src/colors.rs
- src/main.rs
> NO_COLOR support

- src/rules/no_octal.rs
> Fix octal with regex

- src/rules/no_empty_character_class.rs
> Fix no empty character class

- src/rules/no_empty.rs
> fix: no-empty rule

- src/rules/mod.rs
- src/rules/no_namespace.rs
+ `no-namespace`
+ `7 tests about it`
> add no-namespace rule

- src/rules/mod.rs
- src/rules/no_empty_pattern.rs
+ `no-empty-pattern rule`
+ `15 tests about it`
> add no-empty-pattern rule

- src/rules/mod.rs
- src/rules/triple_slash_reference.rs
+ `triple-slash-reference rule`
+ `12 tests about it`
> add triple-slash-reference rule

- README.md
- src/linter.rs
> feat: add deno-lint-file-ignore directive

- src/linter.rs
- src/rules/ban_untagged_ignore.rs
- src/rules/mod.rs
- src/test_util.rs
> Add no-unused-ignore rule

- src/rules/mod.rs
- src/rules/no_this_alias.rs
+ `no-this-alias rule`
+ `14 tests about it`
> add no-this-alias rule

- README.md
- src/rules/mod.rs
- src/rules/no_this_before_super.rs
Related PR: #147 
I forgot to add `no-this-before-super` to README and recommended_rules. Now I've done it.
In addition, I made another test to check it works in case there are more than one class.
> Fix README and recommended_rules about no-this-before-super

- src/rules/no_empty.rs
> Fix no-empty for contructors (#151)

- src/rules/mod.rs
- src/rules/prefer_as_const.rs
+ `prefer-as-const rule`
+ `32 tests about it`
> add prefer-as-const rule

- src/rules/no_ex_assign.rs
this patch handles `Array` and `Object` patterns for destructuring assignment in the catch block.
two new supported warnings :
```ts
(no-ex-assign) Reassigning exception parameter is not allowed
--> .\problem.ts:1:20
|
1 | try {} catch (ex) { [ex] = []; }
|                     ^^^^^^^^^
|
(no-ex-assign) Reassigning exception parameter is not allowed
--> .\problem.ts:2:21
|
2 | try {} catch (ex) { ({x: ex = 0} = {}); }
|                      ^^^^^^^^^^^^^^^^
|
```
> Fix no ex assign

- README.md
Ref https://github.com/denoland/deno_lint/issues/172
> docs: add note about required Rust version

- README.md
- src/rules/mod.rs
- src/rules/no_await_in_loop.rs
This PR is to add [no-await-in-loop - Rules - ESLint](https://eslint.org/docs/rules/no-await-in-loop#top) rule.
Since this rule is not listed as `recommended`, I added it only to `get_all_rules`.
> Add no-await-in-loop rule

- README.md
- src/rules/mod.rs
- src/rules/no_const_assign.rs
this PR is going to add:
- `no-const-assign rule`
- `23 tests about it`
> add no-const-assign rule

- src/scopes.rs
ref https://github.com/denoland/deno_lint/issues/160#issuecomment-647009749
add `Loop` scope kind as follows: 
```ts
for (let i = 0; i < 10; i++){}
for (let i in [1,2,3]){}
for (let i of [1,2,3]){}
while (i > 1) {}
do {} while (i > 1)
```
> scopes: init loop scopes

- src/diagnostic.rs
- src/linter.rs
Fixes https://github.com/denoland/deno_lint/issues/156
Ref https://github.com/swc-project/swc/issues/856
> fix: deduplicate ignore directives

- src/rules/no_dupe_class_members.rs
Fix #189 
And also I made tiny refactoring.
> Do not check methods with no body in no-dupe-class-members

- src/rules/no_const_assign.rs
pre-request #192
add 4 tests about `call/new expressions` and `object literal`
> more tests about no_const_assign

- src/scopes.rs
Ref #160 
This is a prerequisite for `no-import-assign` rule.
> scopes: import binding

- src/lib.rs
- src/linter.rs
- src/test_util.rs
> Lint unknown ignore rule code

- src/scopes.rs
support `rest` pattern as follows :
```ts
[...a] = [ "a" ];
{...b} = { b : "B"};
```
> scopes: rest pattern bindings

- README.md
- src/rules/ban_types.rs
- src/rules/mod.rs
this PR is going to add
- `ban-types rule`
- `24 tests about it`
> add ban-types rule

- src/rules/no_dupe_else_if.rs
I forgot to remove a test created for debugging, so I've removed it.
> chore(no-dupe-else-if): remove a duplicate test

- src/rules/constructor_super.rs
Currently `constructor-super` rule does not handle nested classes, so errors that happen inside a nested class are not reported.
This PR fixes it and adds some tests to make sure it works for nested classes.
> fix(constructor-super): handle nested classes

- src/rules/no_this_alias.rs
Fixes https://github.com/denoland/deno_lint/issues/246
> fix: no-this-alias rule

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/diagnostic.rs
Adds `Serialize` trait to `Location` and `LintDiagnostic` gated behind Cargo feature called `json`.
Closes #253
> feat: add Cargo feature 'json'

- src/lib.rs
- src/linter.rs
- src/rules/no_constant_condition.rs
- src/rules/no_self_assign.rs
Closes #280 
Closes #281
Closes #282 
Closes #283 
Closes #284
> fix: numerous bugs

- examples/dlint/main.rs
- src/diagnostic.rs
- src/linter.rs
- src/test_util.rs
> feat: use position range in diagnostic

- src/rules/no_undef.rs
Closes https://github.com/denoland/deno_lint/issues/321
> no-undef: Ignore `import`

- src/rules/no_unsafe_finally.rs
> fix(no-unsafe-finally): catch violations in nested finally blocks

- src/control_flow/mod.rs
- src/rules/no_unreachable.rs
> Fix no-unreachable

- src/diagnostic.rs
- src/linter.rs
- src/rules/mod.rs
Ref https://github.com/denoland/deno_lint/issues/159
Ref https://github.com/denoland/deno_lint/issues/162
> Add LintRule::docs() and LintDiagnostic::hint

- src/rules/prefer_const.rs
> fix(prefer-const): treat param of catch clause like thet of function

- src/rules/prefer_const.rs
> fix(prefer-const): handle `+=` and `-=` correctly

- src/rules/no_compare_neg_zero.rs
Adds a little more tests and fixes the implementation to make it handle nested stuff.
> fix(no-compare-neg-zero): handle nested stuff

- src/control_flow/mod.rs
- src/rules/no_unreachable.rs
> fix(control_flow): handle class constructors

- src/rules/prefer_const.rs
This PR fixes (partially) #358 
Previously, nested `AssignmentExpression` were reported as errors if the variables within them were declared as `let` without initialization and assigned only once. For example:
```js
let a; // <------ declared as `let` without initialization
const b = (a = foo === bar); // <------- `a` is within  the nested `AssignmentExpression` and assigned only once
```
In this case we should not report `a` as an error, because it couldn't be declared as `const`.
Therefore I've changed the implementation a bit so _nested_ `AssignmentExpression` and _not-nested_ one are handled 
differently.
> fix(prefer-const): handle nested assignments correctly

- .github/workflows/ci.yml
- www/pages/index.tsx
> feat: deploy website

- .github/workflows/ci.yml
Ref https://github.com/denoland/deno/pull/7898
> ci: fix Github Actions cache

- www/components/Header.tsx
- www/pages/_document.tsx
- www/pages/ignoring-rules.tsx
- www/pages/index.tsx
- www/public/ignoring-rules.md
@bartlomieju added the requested `ignoring-rules` page and made some a11y fixes.
> website updates

- src/linter.rs
Ref https://github.com/denoland/deno_lint/pull/396
CC @cknight
> refactor: add API for diagnostic with hint

- src/rules/adjacent_overload_signatures.rs
- src/rules/ban_ts_comment.rs
A small PR just to check this is what is expected.
> doc: add hints

- src/rules/no_constant_condition.rs
What I did in this PR:
- allowing it to handle nested `IfStmt` and `CondExpr`
- removing `swc_ecmascript::ast::` by importing on the top of `no_constant_condition.rs`
> fix(no-constant-condition): handle nested stuff

- src/rules/constructor_super.rs
- src/rules/default_param_last.rs
- src/rules/eqeqeq.rs
This PR:
* Resolves #408 
* Contributes to #159 with docs and hints for `constructor-super`, `default-param-last` and `eqeqeq`
> fix: constructor-super, doc: add lint docs

- examples/dlint/main.rs
> example(dlint): show hints

- src/globals.rs
> fix(no_undef): add AggregateError global

- Cargo.lock
- Cargo.toml
- src/rules/adjacent_overload_signatures.rs
- src/rules/default_param_last.rs
- src/rules/for_direction.rs
- src/rules/no_array_constructor.rs
- src/rules/no_async_promise_executor.rs
- src/rules/no_case_declarations.rs
- src/rules/no_class_assign.rs
- src/rules/no_compare_neg_zero.rs
- src/rules/no_cond_assign.rs
- src/rules/no_constant_condition.rs
- src/rules/no_dupe_args.rs
- src/rules/no_dupe_keys.rs
- src/rules/no_unsafe_finally.rs
Closes https://github.com/denoland/deno_lint/issues/412
Towards #330
> refactor: use swc_ecma_visit::VisitAll

- src/rules/no_array_constructor.rs
- src/rules/no_async_promise_executor.rs
- src/rules/no_await_in_loop.rs
- src/rules/no_case_declarations.rs
This PR add docs for:
* no-array-constructor
* no-async-promise-executor
* no-await-in-loop
* no-case-declaration
> doc: add docs

- src/rules/no_control_regex.rs
- src/rules/no_debugger.rs
- src/rules/no_delete_var.rs
- src/rules/no_dupe_args.rs
- src/rules/no_dupe_class_members.rs
- src/rules/no_dupe_else_if.rs
- src/rules/no_dupe_keys.rs
- src/rules/no_duplicate_case.rs
This PR contributes to #159 adding the following docs:
* no-control-regex
* no-debugger
* no-delete-var
* no-dupe-args
* no-dupe-class-members
* no-dupe-else-if
* no-duplicate-case
> doc: add linting hints and docs

- src/rules/valid_typeof.rs
> refactor(valid-typeof): use assert_lint_err! macro

- src/rules/no_class_assign.rs
Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro in `no-class-assign`.
> refactor(no-class-assign): switch to `assert_lint_err!` macro

- www/pages/index.tsx
> feat: adds back accordion to website

- .github/workflows/ci.yml
> build: release dlint binary on tags

- src/rules/constructor_super.rs
Fixes https://github.com/denoland/deno_lint/issues/464
> fix: constructor-super for declarations

- src/rules/no_empty_pattern.rs
- src/rules/no_eval.rs
- src/rules/no_ex_assign.rs
This PR contributes to #159 with the following rule additions:
* no-empty-pattern
* no-eval
* no-ex-assign
It also adds some commented out tests related to issue #466 (no-eval false negatives)
> doc: add lint hints and docs

- src/rules/no_namespace.rs
Fixes https://github.com/denoland/deno_lint/issues/465
> fix: no-namespace for declared namespaces

- src/control_flow.rs
- src/rules/no_unreachable.rs
> fix control flow analysis on for statements

- src/rules/triple_slash_reference.rs
Closes https://github.com/denoland/deno_lint/issues/461
> chore: remove triple-slash-reference from recommended set

- src/control_flow.rs
- src/rules/getter_return.rs
> fix(ControlFlow): handle block execution status correctly

- src/rules/camelcase.rs
Fixes #416 
Hint message of `camelcase` rule is sometimes unfriendly. Consider the following code:
```ts
const { category_id = 1 } = query;
```
Running `camelcase` on this code, we get a hint like:
`` Consider replacing `{ category_id }` with `{ category_id: categoryId } ``
where the default value `1` is gone. If one is not so familiar with JavaScript / TypeScript, he/she may be confused and cannot figure out how the default value works with the suggested hint.
So this PR changes hint message to:
`` Consider replacing `{ category_id = .. }` with `{ category_id: categoryId = .. } ``
so that it can tell users how to add default values by showing `..` mark.
> fix(camelcase): provide better hint message when object pattern has default value

- src/lib.rs
- src/linter.rs
> fix ban-unused-ignore and ban-unknown-rule-code

- src/rules/no_compare_neg_zero.rs
> refactor(no-compare-neg-zero): switch to `asset_lint_err!` macro

- src/rules/no_cond_assign.rs
> refactor(no-cond-assign): switch to `asset_lint_err!` macro

- src/rules/no_constant_condition.rs
> refactor(no-constant-condition): switch to `asset_lint_err!` macro

- src/rules/no_debugger.rs
> refactor(no-debugger): switch to `asset_lint_err!` macro

- src/rules/no_dupe_else_if.rs
> refactor(no-dupe-else-if): switch to `asset_lint_err!` macro

- src/rules.rs
- src/rules/require_await.rs
> feat: add require-await rule

- src/rules/no_empty_interface.rs
>  refactor(no-empty-interface): switch to `asset_lint_err!` macro

- src/rules/prefer_const.rs
> refactor(prefer-const): switch to `asset_lint_err!` macro

- src/rules/no_extra_semi.rs
Part of #431 
Plus refactors a bit by using `VisitWith`.
> refactor(no-extra-semi): switch to `asset_lint_err!` macro

- src/rules/ban_untagged_todo.rs
Fixes https://github.com/denoland/deno_lint/issues/534
Ref #431
> fix(ban-untagged-todo): make "@" optional

- src/rules/no_fallthrough.rs
> refactor(no-fallthrough): switch to `asset_lint_err!` macro

- Cargo.lock
- Cargo.toml
Also not pinning patch version anymore.
> upgrade: swc_ecmascript, swc_common

- src/rules/no_inferrable_types.rs
This PR fixes `no-inferrable-types` so that it will check private class fields as well.
Also, adds tests to make sure this rule works as expected for the following cases:
- private instance fields
- private static fields
- private instance methods
- private static methods
Fixes #558
> fix(no-inferrable-types): handle private class fields

- src/rules/getter_return.rs
This PR addresses TODO comments in `getter-return` so that the rule will display appropriate error messages in cases where getter functions contain function expression, function declaration, or arrow expression.
For example, running `getter-return` rule on the following code:
```typescript
const foo = {
get bar() {
function f() {
return true;
}
},
};
```
we see `Expected 'bar' to always return a value.`, but after this PR is merged, we will see `Expected to return a value in 'bar'.`
> fix(getter-return): proper handling for function in getter

- www/pages/_document.tsx
This PR adds meta tags for the open graph protocol.
https://ogp.me/
> feat(website): add meta tags for open graph

- src/rules/no_namespace.rs
> refactor(no-namespace): switch to `assert_lint_err!` macro

- src/rules/no_new_symbol.rs
Part of #431 and #330 
- replace with `assert_lint_err!` macro
- use `VisitAll` instead of `Visit`
> refactor(no-new-symbol): switch to `asset_lint_err!` macro

- src/rules/no_regex_spaces.rs
> refactor(no-regex-spaces): switch to `asset_lint_err!` macro

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- www/deps.ts
- www/pages/ignoring-rules.tsx
- www/pages/index.tsx
> chore: update cargo dependencies

- src/rules/no_undef.rs
> fix(no-undef): collect type alias declarations

- .github/workflows/ci.yml
- Cargo.lock
- Cargo.toml
- src/globals.rs
- www/deps.ts
- www/pages/ignoring-rules.tsx
- www/pages/index.tsx
Also adds navigator global in prep for WebGPU.
> chore: update deps

- .github/workflows/ci.yml
Will switch over the main branch once this PR is approved.
> chore: switch default branch to main

- src/rules/no_unreachable.rs
> fix(no-unreachable): ignore type declarations

- src/globals.rs
> Fix: Add `Intl` to Globals list

- .github/workflows/ci.yml
- README.md
- examples/dlint/js.rs
- src/handler.rs
- src/js_regex/mod.rs
- src/js_regex/unicode.rs
- src/js_regex/validator.rs
- src/rules/camelcase.rs
- src/rules/no_const_assign.rs
- src/rules/no_empty_pattern.rs
- src/rules/no_extra_non_null_assertion.rs
- src/rules/no_invalid_regexp.rs
- src/rules/prefer_const.rs
- src/test_util.rs
Upgrades Rust to 1.51.0 and applys clippy's diagnostics.
> Upgrade Rust to 1.51.0

- src/rules/no_namespace.rs
- src/rules/no_this_before_super.rs
- src/rules/no_unused_vars.rs
- src/test_util.rs
> fix(no-namespace): allow `namespace` in ambient context

- src/rules/no_undef.rs
> fix(no-undef): handle `export default` properly

- src/control_flow.rs
> fix(control-flow): don't panic even if there's invalid `break` or `continue` statement

- src/globals.rs
Ref https://github.com/denoland/deno/pull/9685.
> fix: Add Navigator and WorkerNavigator globals

- .github/workflows/ci.yml
~~Not sure if it works so let's see it~~
This workaround seems to work.
> ci: add gnu-tar on macOS as a workaround

- src/rules/prefer_const.rs
> fix(prefer-const): handle switch statements properly

- src/rules/no_unused_vars.rs
- src/test_util.rs
> fix(no-unused-vars): properly mark JSX element names as used

- src/control_flow.rs
- src/rules/no_unreachable.rs
> fix(control-flow): handle `break` statements in loops properly

- src/rules/no_unused_vars.rs
> fix(no-unused-vars): don't trigger errors for `export declare`

- src/globals.rs
See https://github.com/denoland/deno/pull/10365/
> Add `WebSocketStream` to globals

- src/rules/no_unused_vars.rs
> fix(no-unused-vars): properly handle usage in arguments and `FnExpr`

- src/rules/no_unused_vars.rs
> fix(no-unused-vars): handle overloaded constructors

- src/rules/no_unused_vars.rs
> fix(no-unused-vars): don't mark variables in for-of/in syntax as used

- src/rules/use_isnan.rs
Adds the documentation for `use_isnan` rule.
#159
> doc(use_isnan): add doc

- src/rules/ban_ts_comment.rs
Fixes #701
And also refactors the code a little bit.
> fix(ban-ts-comment): enrich hint to include concrete example

- src/rules/adjacent_overload_signatures.rs
Re-implements `adjacent-overload-signatures` with ast-view, and introduces typed message and hint.
> refactor(adjacent-overload-signatures): re-implement with ast-view

- src/rules/no_unreachable.rs
Adds the documentation for `no-unreachable` rule.
#159
> doc(no-unreachable): add doc

- src/rules.rs
- src/rules/no_invalid_triple_slash_reference.rs
- src/rules/no_namespace.rs
- src/rules/no_unused_vars.rs
- src/test_util.rs
> feat: implement new lint `no-invalid-triple-slash-reference`

- examples/dlint/main.rs
Fixes #710
This patch makes the dlint binary available for JSX and TSX.
> fix(dlint): determine syntax config from file extension

- Cargo.lock
- Cargo.toml
- src/rules/no_unused_vars.rs
> fix(no-unused-vars): handle type-only imports correctly

- src/rules/no_invalid_triple_slash_reference.rs
> fix(no-invalid-triple-slash-reference): take `no-default-lib` into account

- src/rules/no_unused_vars.rs
I don't think I precisely understand what is wanted in #730, but I believe this PR fixes #730.
This PR fixes the hint issued by `no-unused-vars` in the case of named imports. Current hint looks like:
```
(no-unused-vars) `foo` is never used
import { foo } from "./foo.ts";
^^^
at /private/tmp/maguro.ts:1:9
hint: If this is intentional, prefix it with an underscore like `_foo`
Found 1 problem
Checked 1 file
```
but this is obviously wrong, because renaming `foo` to `_foo` results in import failure. The hint should suggest aliasing `foo` with an underscore, like `foo as _foo`. So the ideal hint would be:
```
error[no-unused-vars]: `foo` is never used
--> maguro.ts:1:10
|
1 | import { foo } from "./foo.ts";
|          ^^^
|
= help: If this is intentional, alias it with an underscore like `foo …
```
> fix(no-unused-vars): suggest aliasing in the case of named imports

- src/rules/constructor_super.rs
Reimplements `constructor-super` with ast-view.
> refactor(constructor-super): reimplement with ast-view

- src/rules/no_unused_vars.rs
> fix(no-unused-vars): handle es private overloaded methods

- src/rules/valid_typeof.rs
> fix(valid-typeof): handle cases when operand is template literals

- src/rules/no_deprecated_deno_api.rs
We're going to deprecate `Deno.customInspect` Symbol in favor of `Symbol.for("Deno.customInspect")` to make it easier to write isomorphic code. issue: https://github.com/denoland/deno/issues/9294, pr: https://github.com/denoland/deno/pull/10035
This PR adds `Deno.customInspect` API to `no-deprecated-deno-api` rule to warn the above deprecation.
> feat: add Deno.customInspect to no-deprecated-deno-api rule

- src/rules/no_fallthrough.rs
Fixes #746
(The second bug reported in #746 hasn't been fixed by this PR though. It isn't reproduced in my environment.)
> fix(no-fallthrough): handle empty block in SwitchCase correctly

- examples/dlint/config.rs
> fix(dlint): make sure the same rule will be run just once

- examples/dlint/main.rs
This patch replaces `try_each` with `try_for_each` in `dlint`, which allows us to use `?` operator inside the closure. As a result, we can propagate errors from inside the closure to outside. The benefit of this is that we can remove `expect` calls on `Option` so that users will get a little bit user-friendly error messages with Rust's default panic messages removed, like:
```
Error: Unexpected token `)`. Expected this, import, async, function, [ for array literal, { for object literal, @ for decorator, function, class, null, true, false, number, bigint, string, regexp, ` for template literal, (, or an identifier at maguro.ts:3:4
```
For comparison, the previous error message looked like:
```
thread 'main' panicked at 'Failed to lint: SwcDiagnosticBuffer { diagnostics: ["Unexpected token …
```
> refactor(dlint): use `try_for_each` instead of `for_each`

- Cargo.lock
- Cargo.toml
Depends on https://github.com/dprint/dprint-swc-ecma-ast-view/pull/26﻿
> update swc + 0.8.0

- src/rules/ban_types.rs
> fix(ban-types): suggest `Record<string, never>` when encountering `{}`

- examples/dlint/main.rs
- src/rules.rs
- src/rules/prefer_primordials.rs
Resolves #757 
I tested if this rule works fine for the actual code. Please see https://github.com/denoland/deno/pull/11500/
> feat: implement new lint `prefer-primordials`

- src/rules/no_redeclare.rs
This PR adds documentation for `no-redeclare`.
> docs(no-redeclare): add docs

- docs/rules/no_regex_spaces.md
Rendered: https://github.com/magurotuna/deno_lint/blob/c55ec78e9b8a340cd016c66208bdeae59da6b694/docs/rules/no_regex_spaces.md
> docs(no-regex-spaces): add docs

- docs/rules/no_self_assign.md
Rendered: https://github.com/magurotuna/deno_lint/blob/76288d5033d199bf90d12239ebff73092573a068/docs/rules/no_self_assign.md
> docs(no-self-assign): add docs

- docs/rules/no_setter_return.md
Rendered: https://github.com/magurotuna/deno_lint/blob/06f88214221cde4167ae45baf67e5cdaa4360187/docs/rules/no_setter_return.md
> docs(no-setter-return): add docs

- docs/rules/no_shadow_restricted_names.md
Rendered: https://github.com/magurotuna/deno_lint/blob/834d6af98c67a5775713d868e1b2beeac17791d7/docs/rules/no_shadow_restricted_names.md
> docs(no-shadow-restricted-names): add docs

- docs/rules/no_this_alias.md
Rendered: https://github.com/magurotuna/deno_lint/blob/1e1a96448ba2118ac9fe7e571fefaf9ec564fdbb/docs/rules/no_this_alias.md
> docs(no-this-alias): add docs

- docs/rules/no_this_before_super.md
Rendered: https://github.com/magurotuna/deno_lint/blob/8b14f56ad6ab8e58071a249774f5d6f1710f37c6/docs/rules/no_this_before_super.md
> docs(no-this-before-super): add docs

- docs/rules/no_unused_vars.md
Rendered: https://github.com/magurotuna/deno_lint/blob/de4ebf24fb3e6b0f60373ccb6ef3ddff03b01e41/docs/rules/no_unused_vars.md
> docs(no-unused-vars): add docs

- docs/rules/prefer_as_const.md
Rendered: https://github.com/magurotuna/deno_lint/blob/c21a01c6d133cd60605afd5512f8713aa735869b/docs/rules/prefer_as_const.md
> docs(prefer-as-const): add docs

- docs/rules/prefer_const.md
- src/rules/prefer_const.rs
Rendered: https://github.com/magurotuna/deno_lint/blob/5b821805dbc1e4d3d688e2ecfe1cbe32ad399adf/docs/rules/prefer_const.md
> docs(prefer-const): add docs

- docs/rules/prefer_namespace_keyword.md
Rendered: https://github.com/magurotuna/deno_lint/blob/063f884837801eae74c2dbbb4884f63bb6baf952/docs/rules/prefer_namespace_keyword.md
> docs(prefer-namespace-keyword): add docs

- src/rules/no_undef.rs
- src/scopes.rs
This PR removes the rule-dedicated scope analyzer from `no-undef`, and instead lets it use the common scope analyzer.
Towards #492
> refactor(no-undef): remove its own scope analyzer

- src/rules/no_deprecated_deno_api.rs
This PR fixes `no-deprecated-deno-api` so that it can correctly handle cases where `Deno` is shadowed in another scope.
> fix(no-deprecated-deno-api): handle cases where `Deno` is shadowed in another scope

- docs/rules/no_empty_enum.md
- src/rules.rs
- src/rules/no_empty_enum.rs
https://github.com/denoland/deno_lint/issues/745
> add lint rule for empty enums

- src/rules/eqeqeq.rs
> Migrate eqeqeq from Visitor to Handler

- src/rules/default_param_last.rs
> Migrate default-param-last from Visitor to Handler

- src/rules/explicit_function_return_type.rs
> Migrate explicit_function_return_type from Visitor to Handler

- src/rules/no_async_promise_executor.rs
> Migrate no_async_promise_executor from Visitor to Handler

- src/rules/no_array_constructor.rs
> Migrate no_array_constructor from Visitor to Handler

- src/rules/for_direction.rs
All test passed, but could you review carefully please.
> Migrate for_direction from Visitor to Handler

- src/rules/no_case_declarations.rs
> Migrate no_case_declarations from Visitor to Handler

- src/rules/explicit_module_boundary_types.rs
> refactor(explicit-module-boundary-types): migrate to Handler

- src/rules/no_compare_neg_zero.rs
part of https://github.com/denoland/deno_lint/issues/818
> Migrate no_compare_neg_zero from Visitor to Handler

- src/rules/no_cond_assign.rs
Part of https://github.com/denoland/deno_lint/issues/818
> Migrate no_cond_assign from Visitor to Handler

- www/deps.ts
- www/server_deps.ts
This reverts commit 4c461c7ad088540c5bcb5fc54b70ae4d234c1f67.
> Revert "fix(www): use fixes version of fresh (#915)"

- www/deps.ts
- www/main.ts
- www/public/ignoring-rules.md
- www/server_deps.ts
- fix: pin fresh to a commit
- chore: deno fmt
> fix: pin fresh to a commit

- src/rules/no_debugger.rs
part of https://github.com/denoland/deno_lint/issues/818
> Migrate no_debugger from Visitor to Handler

- src/rules/no_delete_var.rs
part of https://github.com/denoland/deno_lint/issues/818
> Migrate no_delete_var from Visitor to Handler

- src/rules/no_control_regex.rs
- src/rules/no_regex_spaces.rs
- src/swc_util.rs
Part of https://github.com/denoland/deno_lint/issues/818
> Migrate no_control_regex and no_regex_spaces from Visitor to Handler

- src/rules/no_empty_interface.rs
> Migrate no_empty_interface from Visitor to Handler

- src/rules/no_empty_character_class.rs
> Migrate no_empty_character_class from Visitor to Handler

- src/rules/no_dupe_keys.rs
> Migrate no_dupe_keys from Visitor to Handler

- src/rules/no_dupe_args.rs
> Migrate no_dupe_args from Visitor to Handler

- src/rules/use_isnan.rs
Ref: https://github.com/eslint/eslint/blob/d867f8100737bb82742debee2b5dc853c5f07c91/tests/lib/rules/use-isnan.js#L24-L51
> test(use-isnan): Add valid case

- src/rules/camelcase.rs
As discussed on Discord.
CC @Soremwar @Skillz4Killz you might be interested in this change
> camelcase: remove from recommended set

- src/rules/require_await.rs
> refactor(require-await): use `Handler` instead of `Visitor`

- src/rules/prefer_primordials.rs
> fix(prefer-primordials): add check for `instanceof` operator

- www/public/docs.json
> fix(website): remove "recommended" tag from `camelcase`

- src/ignore_directives.rs
File-level ignore directives were being looked for in the leading comments before the first token in the program, but when the file has a shebang, the shebang is the first token, and so no comments are returned. This change makes it so, if the program has a shebang, the directives are looked for immediately before the first statement or declaration, if any, or at the end of the program otherwise.
Closes #999.
> fix: Allow `deno-lint-ignore-file` comments after a shebang

- src/rules/prefer_namespace_keyword.rs
fix https://github.com/denoland/deno_lint/issues/1004
> fix: typo in "prefer-namespace-keyword"

- src/rules/getter_return.rs
> fix(getter-return): return statement inside the `method_prop` dont have effect on outside of it

- src/rules/no_invalid_triple_slash_reference.rs
This commit allows to use `/// <reference path="path" />` in JavaScript files.
Fixes #982
> fix: 'no-invalid-triple-slash-referecence' on path reference for JavaScript files

- src/rules/no_deprecated_deno_api.rs
> fix(no-deprecated-deno-api): handle type annotations

- Cargo.lock
- Cargo.toml
- src/control_flow/mod.rs
- src/rules/adjacent_overload_signatures.rs
> release 0.27.0

- src/control_flow/analyze_test.rs
- src/control_flow/mod.rs
- src/rules/no_unreachable.rs
> fix(control-flow): analyze try statements in correct order

- src/rules/explicit_module_boundary_types.rs
> fix(explicit-module-boundary-types): ignore js(x) files

- src/rules/explicit_function_return_type.rs
> fix(explicit-function-return-type): ignore js(x) files (#1055)

- www/pages/index.tsx
> fix: details summary rendering

- docs/rules/no_implicit_declare_namespace_export.md
- src/rules.rs
- src/rules/no_implicit_declare_namespace_export.rs
> feat: add no-implicit-declare-namespace-export (#1057)

- www/pages/index.tsx
- www/public/docs.json
- www/public/extension.css
> feat: Style valid and invalid examples

- src/rules/prefer_const.rs
Closes https://github.com/denoland/deno_lint/issues/1065
> fix(prefer-const): don't skip expressions assigned to function parameters

- rust-toolchain.toml
- src/rules/camelcase.rs
- src/rules/for_direction.rs
- src/rules/no_array_constructor.rs
- src/rules/no_constant_condition.rs
- src/rules/no_dupe_else_if.rs
- src/rules/no_import_assign.rs
- src/rules/no_invalid_regexp.rs
- src/rules/no_self_assign.rs
- src/rules/prefer_const.rs
- src/swc_util.rs
- src/test_util.rs
With this PR the following things are done:
- Upgrade to Rust 1.64
- Apply fixes according to clippy
> chore: upgrade Rust to 1.64

- src/rules/getter_return.rs
- Fixed to check the return value of get property in `Object.create` and `Object.defineProperties`.
> fix: getter_return - checking the return value in `Object.create` and `Object.defineProperties`

- src/rules/getter_return.rs
getter_return rules permit using generator without explicit return value.
> fix: getter_return - permit using a generator without specifying an explicit return value

- .github/workflows/ci.yml
- www/public/docs.json
This commit updates `www/public/docs.json` and adds a new CI step to check if this file is up-to-date.
> chore(docs): update `www/public/docs.json` & add a CI step to check if it's up-to-date

- docs/rules/guard_for_in.md
- src/rules.rs
- src/rules/guard_for_in.rs
- www/public/docs.json
> feat: Add guard-for-in rule

- examples/dlint/config.rs
- src/rules.rs
More details and alternative solution in https://github.com/denoland/deno/issues/17161#issuecomment-1364092487
Also reworded some tests and updated assertions.
Fixes https://github.com/denoland/deno/issues/17161
> ref: Exclude rules takes precedence over include

- src/rules/prefer_primordials.rs
Detects the `Symbol.iterator` method being called by `yield*`.
```js
// prototype pollution
const original = Array.prototype[Symbol.iterator];
Array.prototype[Symbol.iterator] = function () { console.log("bang!"); return original.call(this); };
function* generator() {
yield* [1, 2, 3];
}
generator().next(); // bang!
```
> feat(prefer-primordials): Add check for `yield*`

- .github/workflows/ci.yml
Updates setup-node from v2 beta to v3 and node from 14 to 18
> ci: update setup-node to v3 and node to 18

- src/rules/prefer_primordials.rs
Closes #1112 
Since I reordered the functions in the second commit, it is easy to check the diffs on a per-commit base.
> feat(prefer-primordials): Add check for getter properties

- www/pages/ignoring-rules.tsx
- www/pages/index.tsx
Fixes https://github.com/denoland/deno_lint/issues/1126
---
> fix: Update syntax hightlighting css file and set 100vh container

- src/rules/prefer_primordials.rs
> fix(prefer-primordials): Check whether safe primordials are used

- README.md
These commands need to be run when contributing a new rule.
> docs: add rule export command

- foo.js
- src/context.rs
- src/rules/require_await.rs
> fix(require_await): use more focused span

- examples/dlint/testdata/issue1145_no_trailing_newline.out
- src/rules/no_var.rs
> fix(no_var): report diagnostic on var keyword

- src/rules.rs
- www/static/docs.json
For https://github.com/denoland/deno/issues/20187
> fix: add no-console to rules

- docs/rules/no_self_compare.md
- src/rules.rs
- src/rules/no_self_compare.rs
- www/static/docs.json
> feat: add no-self-compare rule

- www/static/ignoring-rules.md
Update doc for PR #1229 
References
1. https://github.com/denoland/deno_lint/issues/1076
2. #1229 
---
cc @bartlomieju
> Specify reasons for ignore directives

- src/rules/no_inferrable_types.rs
- www/static/docs.json
This rule clashes with JSR's suggestions.
> feat: no-inferrable-types is not in recommended set

- Cargo.lock
- Cargo.toml
- src/context.rs
- src/diagnostic.rs
- src/rules/no_window.rs
- src/rules/no_window_prefix.rs
- src/test_util.rs
> feat: quick fixes

- www/components/Header.tsx
Hi
This way users can learn:
- how to run the CLI with various flags
- how to configure the `deno.json` `lint` entry
> feat(www): add header link to official docs

- .github/workflows/ci.yml
For https://github.com/denoland/deno/pull/24041
> fix: use macos-13 runner

- src/rules/prefer_primordials.rs
related: https://github.com/denoland/deno/pull/24396
> fix(prefer-primordials): add ES2024 ArrayBuffer features

- docs/rules/no_node_globals.md
- src/rules/no_node_globals.rs
- www/static/docs.json
Reverts denoland/deno_lint#1328
> Revert "fix: remove process global check"

- src/rules/rules_of_hooks.rs
Fixes https://github.com/denoland/deno_lint/issues/1393
> fix(rules-of-hooks): fix incorrect hook detection

- src/rules/button_has_type.rs
We don't have enough information in the plain AST to deduce if any expression results into a valid value because we don't have type information. Therefore we'll treat these cases as valid.
```jsx
// Valid
<button {...props} />
<button type={type} />
<button type={type()} />
```
Fixes https://github.com/denoland/deno_lint/issues/1392
> fix(button-has-type): treat expressions as valid value

- src/rules/jsx_button_has_type.rs
- src/rules/react_no_danger.rs
- src/rules/react_no_danger_with_children.rs
Fixes https://github.com/denoland/deno_lint/issues/1391
> fix: only mark relevant JSX nodes for failing rule

- src/rules/jsx_no_unescaped_entities.rs
Fixes https://github.com/denoland/deno_lint/issues/1399
> fix(jsx_no_unescaped_entities): only warn about > and }

- src/rules/no_var.rs
> fix: `no-var` case in TS declaration

- src/rules/jsx_boolean_value.rs
Also doesn't remove if there's comments in the expr.
> fix(jsx-boolean-value): add code fix
