denoland/deno_lint

README.md
src/linter.rs

Changes the ignore directive from `deno:ignore` to `deno-lint-ignore` as per #27.

Change ignore directive to deno-lint-ignore

---

.github/workflows/ci.yml

actions/cache released v2.
https://github.com/actions/cache/releases/tag/v2.0.0

Bump actions/cache version from v1 to v2.

---

src/rules/ban_ts_ignore.rs
src/rules/ban_untagged_todo.rs
src/test_util.rs

@bartlomieju If this seems good then I'll move all of the other tests over to the new utils. I did ultimately keep a line number version of the utils because it seems useful for the multi line tests (the comment related ones for example).

refactor: Testing utils

---

Cargo.lock
Cargo.toml
src/main.rs
src/rules/mod.rs
src/rules/no_class_assign.rs
src/rules/no_ex_assign.rs
src/rules/no_func_assign.rs
src/scopes.rs

This commit adds basic scope analysis and two lint rules
that require such analysis:
- noFuncAssign
- noClassAssign
Scope analysis visits only a few nodes and needs to be
finished.

Basic scope analysis, noFuncAssign, noClassAssign

---

.github/workflows/ci.yml

actions/checkout released v2.
https://github.com/actions/checkout#checkout-v2

Bump actions/checkout version from v1 to v2.

---

src/diagnostic.rs
src/linter.rs

the current report format of multiline snippets : 
```ts
function multiple(num: number) {
}
```
```shell
(explicitFunctionReturnType) Missing return type on function
--> ./problem.ts:1:0
|
1 | function multiple(num: number) {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
(noEmpty) Empty block statement
--> ./problem.ts:1:31
|
1 | function multiple(num: number) {
|                                ^^^^^^^^^^
|
(noEmptyFunction) Empty functions are not allowed
--> ./problem.ts:1:0
|
1 | function multiple(num: number) {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
}
```
should be :
```shell
(explicitFunctionReturnType) Missing return type on function
--> ./problem.ts:1:0
|
1 | function multiple(num: number) {
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
(noEmpty) Empty block statement
--> …
```

(fix-report) Multiple clutter lines

---

src/rules/no_octal.rs

the octal rule mistakenly complains about `0` number.

fix octal rule about 0 number

---

src/diagnostic.rs

Before:
```
(noEmptyCharacterClass) empty character class in RegExp is not allowed
--> ../deno/std/http/file_server.ts:169:44
|
169 |   const formattedDirUrl = `${dirUrl.replace(/\/$/, "")}/`;
|                                             ^^^^^
|
```
After:
```
(noEmptyCharacterClass) empty character class in RegExp is not allowed
--> ../deno/std/http/file_server.ts:169:44
|
169 |   const formattedDirUrl = `${dirUrl.replace(/\/$/, "")}/`;
|                                             ^^^^^
|
```

fix: line reference formatting in diagnostic

---

src/rules/no_empty_function.rs

this PR is going to support `nested` functions in no-empty-functions rule
current behavior :
```ts
function a(){
function b(){}
}
```
deno lint : `nothing about empty function of 'b'.`
eslint : `2:17  warning  Unexpected empty function 'b'                  no-empty-function`
after this patch : 
```shell
(no-empty-function) Empty functions are not allowed
--> .\problem.ts:2:4
|
2 |     function b(){}
|     ^^^^^^^^^^^^^^
|
```

fix no-empty-function rule

---

src/rules/explicit_function_return_type.rs

this PR is going to support nested functions in explicit-function-return-type rule.
ref #119.

fix: explicit-function-return-type rule

---

src/rules/ban_ts_comment.rs
src/rules/mod.rs

+ `ban-ts-comment rule`
+ `25 tests about it`
_ps: `@ts-check` is allowed by default on tslint._

add ban-ts-comment rule

---

src/rules/getter_return.rs

fixes #168.
as mentioned in #168, this rule should analyze the flow ( `if and switch statements` ) for return statement.
30 more tests were also added.

fix getter-return rule

---

src/scopes.rs

ref #160.
add destructuring assignment support for `var declarations`, `function params` , `catch block`.
nested destructuring like following now supported :
```ts
// code : 
const {a,b : {c, d :[e, f]}} = {a: "a", b: {c: "c", d: ["e", "f"]}};
// bindings : 
{
"e": Binding { kind: Const, name: "e" }, 
"c": Binding { kind: Const, name: "c" }, 
"a": Binding { kind: Const, name: "a" },
"f": Binding { kind: Const, name: "f" }
}
```

[scopes] destructuring assignment support

---

src/rules/no_cond_assign.rs

this rule should warn about assignments in conditional expressions like the following :
```ts
let x; let b = (x = 0) ? 1 : 0;
^^^^^^^
```

fix: no-cond-assign [ warn about conditional expressions ]

---

README.md
src/rules/mod.rs
src/rules/no_dupe_class_members.rs

~This is WORK IN PROGRESS.~
(UPDATE) Completed.
This PR is to add [no-dupe-class-members](https://eslint.org/docs/2.0.0/rules/no-dupe-class-members) rule.
Almost all tests are brought from [eslint/no-dupe-class-members.js at master · eslint/eslint](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-dupe-class-members.js), and I implemented the code to pass the tests.

Add no-dupe-class-members rule

---

README.md
src/rules/mod.rs
src/rules/no_dupe_class_members.rs
src/rules/no_extra_boolean_cast.rs

~This is WORK IN PROGRESS.~
(UPDATE) Completed.
This PR is to add [no-extra-boolean-cast](https://eslint.org/docs/rules/no-extra-boolean-cast) rule.
Almost all rules are brought from [here](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-extra-boolean-cast.js), and some original tests are also added.
This rule has an option `enforceForLogicalOperands`, which is `false` by default. The implementation in this PR assumes that this option is set to `false`.

no-extra-boolean-cast

---

README.md
src/rules/mod.rs
src/rules/no_dupe_else_if.rs
src/swc_util.rs
src/test_util.rs

~This is WORK IN PROGRESS~
This PR adds [no-dupe-else-if - Rules - ESLint - Pluggable JavaScript linter](https://eslint.org/docs/rules/no-dupe-else-if) rule.
The original implementation is [here](https://github.com/eslint/eslint/blob/master/lib/rules/no-dupe-else-if.js), and it's so complicated.
I did my best to port the original implementation, but the code got dirty, although all the tests are passed.
Also I'm concerned about bad time complexity and cloning `Vec` many times, which may cause bad performance.

no-dupe-else-if

---

src/rules/eqeqeq.rs

This PR is going to:
- add more tests for `eqeqeq` (brought from [ESLint's tests](https://github.com/eslint/eslint/blob/master/tests/lib/rules/eqeqeq.js))
- enable to deal with nested `==` / `!=`
- change the behavior on comparison with `null`. The previous behavior worked as if the `{"null": "ignore"}` option was being enabled, and it is not the default option. After this PR gets merged, this rule will follow the default option. ref: https://eslint.org/docs/rules/eqeqeq

Fix eqeqeq

---

src/rules/no_empty_interface.rs

This PR 
- adds more tests for `no-empty-interface`
- changes error messages according to the number of superclass
- allows an interface to have more than one superclass (ref: https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/no-empty-interface.md)

Fix no-empty-interface

---

README.md

I found `no-extra-non-null-assertion` was not mentioned in README. I've just added it.

chore(no-extra-non-null-assertion): add to readme

---

Cargo.lock
Cargo.toml
README.md
src/rules/mod.rs
src/rules/no_extra_semi.rs

~WORK IN PROGRESS~
~waiting for swc's patch to be completed.~
This PR adds the [`no-extra-semi`](https://eslint.org/docs/rules/no-extra-semi) rule.
Updating `swc` is required to parse empty statements in class properly.

no-extra-semi

---

Cargo.lock
Cargo.toml
examples/dlint/main.rs
src/lib.rs
src/linter.rs

Closes https://github.com/denoland/deno_lint/issues/225
Adds basic logging using `log` crate taking measurements for critical methods.
Output can be tested in example by using `RUST_LOG=debug target/debug/examples/dlint <files>`

chore: add debug logging with basic timers

---

README.md
src/rules/adjacent_overload_signatures.rs
src/rules/mod.rs
src/rules/no_dupe_keys.rs
src/swc_util.rs
src/test_util.rs

~~WORK IN PROGRESS~~
This PR adds the [`adjacent-overload-signatures`](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/adjacent-overload-signatures.md) rule.

adjacent-overload-signatures

---

README.md
src/rules/mod.rs
src/rules/no_unexpected_multiline.rs

This PR adds the [`no-unexpected-multiline`](https://eslint.org/docs/rules/no-unexpected-multiline) rule.
Updating swc is required to handle optional chaining (in ES2020) correctly, as is also marked through TODO comments.

Add no-unexpected-multiline rule

---

src/rules/explicit_module_boundary_types.rs
src/rules/mod.rs

[Specification](https://github.com/typescript-eslint/typescript-eslint/blob/master/packages/eslint-plugin/docs/rules/explicit-module-boundary-types.md)
What is currently working:

feat: add explicit-module-boundary-types

---

Cargo.lock
Cargo.toml
src/rules/mod.rs
src/rules/no_unused_vars.rs
src/swc_util.rs
src/test_util.rs

I may split swc_emca_transforms with features (or multiple crates) to reduce compile time...

Add no-unused-vars rule 

---

src/linter.rs

This is a so trivial patch; unnecessary string allocation has been removed.
With regard to replacing `contains()` with `iter().any()`, I referred to [the std library document](https://doc.rust-lang.org/std/primitive.slice.html#method.contains) .
> If you do not have an `&T`, but just an `&U` such that `T: Borrow<U>` (e.g. `String: Borrow<str>`), you can use `iter().any`

chore: remove unnecessary allocation

---

Cargo.lock
Cargo.toml
benchmarks/benchmarks.ts
examples/dlint/main.rs

This commit adds `rayon` dev dependency. 
It is used in `dlint` example to run linter on a threadpool.

example: use rayon for threaded execution

---

README.md
src/lib.rs
src/linter.rs

Closes https://github.com/denoland/deno_lint/issues/255
This PR adds support for ignoring rule in whole file, by allowing `// deno-lint-ignore-file` directive to take rule codes to be ignored.

feat: ignore rule in file

---

src/rules/no_undef.rs

This is very naive patch but it will be enough for most users as main purpose of the lint is catching typo.
Closes #317

no-undef: Ignore arguments

---

src/control_flow/mod.rs
src/rules/no_unreachable.rs

This pr fixes the linter by checking if there's a default case.
Fixes #318

no-unreachable: Fix false positive of switch

---

src/rules/default_param_last.rs

Just like #327, `default-param-last` doesn't handle violations in nested functions, so I've fixed it.
Moreover, it doesn't check arrow functions. Fixed it as well.

fix(defualt-param-last): handle nested violations

---

src/lib.rs
src/test_util.rs

This patch allows tests to print source code when an assertion fails. It will show us which test case has failed.
Currently, if there are many test cases in one test function and one of them fails, it's a little difficult to know which test has failed. For example, we write many assertions in one function:
```rust
#[test]
fn no_with() {
assert_lint_err::<NoWith>("with (someVar) { console.log('asdf'); }", 0);
assert_lint_err::<NoWith>("with (foo) { }", 0);
assert_lint_err_n::<NoWith>(
"with (bar) { with (a) { } const a = 42; }",
vec![0, 13],
);
assert_lint_err::<NoWith>("with (baz) { let b = 1; }", 0);
assert_lint_err_n::<NoWith>(
"with (a) { with (b) { console.log('oh no'); } }",
vec![0, 11],
);
assert_lint_err::<NoWith>("with (x) { console.log('alice'); }", 0); …
```

test: print source code when assertion fails

---

src/rules/for_direction.rs

`for-direction` currently doesn't deal with nested for-loops. I have fixed it.

fix(for-direction): handle nested for loops

---

src/rules/getter_return.rs

~~WIP~~
This PR allows `getter-return` to handle nested stuff and adds some more tests.

fix(getter-return): handle nested stuff

---

src/rules/no_array_constructor.rs

This PR allows `no-array-constructor` to handle nested stuff.

fix(no-array-constructor): handle nested stuff

---

src/rules/no_async_promise_executor.rs

This is a part of #330
This PR allows `no-async-promise-executor` to handle nested or parenthesized stuff.

fix(no-async-promise-executor): handle nested or parenthesized stuff

---

README.md
src/lib.rs
src/rules/mod.rs
src/rules/prefer_const.rs

Closes #337 
This PR adds [prefer-const](https://eslint.org/docs/rules/prefer-const).
I feel like it's ad-hoc, or a little dirty implementation, and has room for being refactored. But all the tests from ESLint are passed except for one case.

add prefer-const rule

---

src/rules/no_empty.rs

Implements the `doc` method for the `no-empty` rule as per #159.
@bartlomieju can you let me know if you're happy with the general text content, format, etc.? :slightly_smiling_face:

Implement `doc` Method for `no-empty` Rule

---

src/rules/valid_typeof.rs

Adds the `docs` method to the `valid-typeof` rule as per #159.

Add `docs` Method for `valid-typeof` Rule

---

src/rules/no_cond_assign.rs

Adds the `doc` method to the `no_cond_assign` rule as per #159.

Added `doc` Method for `no_cond_assign` Rule

---

src/rules/prefer_const.rs
src/test_util.rs

~~WIP~~
Fixes #358 
This PR looks quite big, but the policy of this change is just simple.
It introduces a new visitor called `VariableCollector`, which is in charge of collecting variable declarations per scope. And the job of `PreferConstVisitor` has changed to visiting any assignments and updating the variable statuses (initialized, reassigned, etc.). This change is required to handle hoisting correctly.
(Previously `PreferConstVisitor` did both collecting declarations and visiting assignments by itself)
I've confirmed that the false positives that were reported against Deno's std are all fixed by this change.

fix(prefer-const): refactor & handle hoisting

---

src/rules/mod.rs

I forgot to turn on `prefer-const` in #362 . I think it's ready to be landed 👍

chore: enable prefer-const again

---

src/rules/no_dupe_keys.rs

Adds the `docs` method for the `no-dupe-keys` rule as per #159.

Add `docs` Method for `no-dupe-keys` Rule

---

src/rules/no_compare_neg_zero.rs

Adds `docs` method for the `no-compare-neg-zero` rule as per #159.

Added `docs` Method for `no-compare-neg-zero` Rule

---

src/rules/no_unsafe_finally.rs

Adds the `docs` method to the `no-unsafe-finally` rule as per #159.

Adds `docs` Method for `no-unsafe-finally` Rule

---

src/linter.rs
src/rules/ban_ts_comment.rs
src/rules/ban_ts_ignore.rs
src/rules/ban_untagged_ignore.rs
src/rules/ban_untagged_todo.rs
src/rules/triple_slash_reference.rs

- `leading_comments`
- `trailing_comments`
- `ignore_directives`
- `scope`
- `control_flow`
The above fields of `Context` struct are declared with `Arc` or `Rc` now, but it seems unnecessary so I removed them.
If `Arc` and `Rc` are removed, it will cost us a lot to call `.clone`. To address it, I refactored some implementations so that unnecessary cloning won't happen.

refactor: remove Arc/Rc

---

.github/workflows/ci.yml
README.md
src/control_flow/mod.rs
src/rules/no_compare_neg_zero.rs
src/rules/no_dupe_class_members.rs
src/rules/no_extra_boolean_cast.rs
src/rules/no_shadow_restricted_names.rs
src/rules/valid_typeof.rs

clippy has started to complain about not using `matches!`. I refactored the code according to clippy.

refactor: use matches!

---

src/control_flow/mod.rs
src/lib.rs
src/rules/getter_return.rs
src/rules/no_unreachable.rs
src/swc_util.rs

Currently, `getter-return` rule only checks `if` and `switch` statements, so it doesn't handle more complicated cases such as including `while` loops.
This PR allows `getter-return` to use `ControlFlow` to check if getters return something, which will make it possible to handle complicated cases.
Fixes #348

fix(getter-return): use ControlFlow to check if getters return something

---

src/linter.rs
src/rules/adjacent_overload_signatures.rs
src/rules/ban_types.rs
src/rules/no_control_regex.rs
src/rules/no_dupe_class_members.rs
src/rules/no_dupe_keys.rs
src/rules/no_inner_declarations.rs
src/rules/no_obj_calls.rs
src/rules/no_prototype_builtins.rs
src/rules/no_self_assign.rs
src/rules/no_shadow_restricted_names.rs
src/rules/no_undef.rs
src/rules/no_unsafe_finally.rs
src/rules/no_unused_labels.rs
src/rules/no_unused_vars.rs
src/rules/prefer_const.rs

Currently `Context::add_diagnostic` method receives code and message with `&str`.
It results in unnecessary allocation because the callers of `add_diagnostic` often pass a message like `&format!("foo {}", bar)`. 
It'd be better to pass the built `String` value (not reference) to`add_diagnostic` for efficiency.
So, I switched their types to `impl Into<String>`, which will allow us to build and allocate new `String` only if that's required.

refactor: switch to `impl Into<String>` to avoid unnecessary allocation

---

Cargo.lock
Cargo.toml
examples/dlint/main.rs
src/diagnostic.rs
src/linter.rs

This commit updates "dlint" example to use "annotate-snippets" crate
for diagnostic formatting. It allows to remove custom formatting implementation
(which was supposed to look the same) as well as colors implementation.
Closes https://github.com/denoland/deno_lint/issues/386
```
error[no-explicit-any]: `any` type is not allowed
--> ./benchmarks/oak/router.ts:6:27
|
1 | /**
2 |  * Adapted directly from @koa/router at
3 |  * https://github.com/koajs/router/ which is licensed as:
4 |  *
...
899 |
900 |     return this as Router<any, any>;
|                           ^^^
|
error[no-explicit-any]: `any` type is not allowed
--> ./benchmarks/oak/router.ts:6:32
|
1 | /**
2 |  * Adapted directly from @koa/router at
3 |  * https://github.com/koajs/router/ which is licensed as:
4 |  *
...
899 |
900 …
```

example(dlint): use annotate-snippets for diagnostic formatting

---

src/rules/no_empty.rs

Allows `no-empty` to be able to handle nested empty blocks in switch's discriminant, and did small refactoring.

fix(no-empty): handle nested empty blocks in switch

---

src/rules/adjacent_overload_signatures.rs
src/rules/ban_ts_comment.rs

Dipping my toe into #159, this add docs for `adjacent-overload-signatures` and `ban-ts-comment`.  
As an aside, `ban-ts-comment` as a name is confusing.  This lint rule does not ban any TS directives (as is the default intent of the eslint equivalent), but instead only allows them with comments/descriptions (which is confusing considering the name).  I've updated the rule diagnostic text to reflect this, but if we aren't tied to eslint's names something like `no-ts-directive-without-comment` or some such might be more descriptive.

doc: Add markup docs for rules

---

src/rules/adjacent_overload_signatures.rs
src/rules/ban_ts_comment.rs
src/rules/ban_types.rs
src/rules/ban_untagged_ignore.rs
src/rules/ban_untagged_todo.rs

This PR:
* Adds clarity in comments to the differences in `ban-ts-comment` between typescript-eslint and deno lint
* Adds documentation to `ban-types`, `ban-untagged-ignore` and `ban-untagged-todo`

doc: Additional docs for a few rules

---

src/rules/no_dupe_args.rs

What I did in this PR:
- allowing to handle nested function's arguments
- removing unnecessary allocation in `check_params` and `check_pats`
- adding more tests

fix(no-dupe-args): handle nested function's arguments and remove unnecesarry allocation

---

src/diagnostic.rs
src/lib.rs
src/rules/no_undef.rs
src/test_util.rs

Closes #395 
There's a difference in the interface of macro from what I proposed in #395, because I have to deal with multiple errors against one source code.
```rust
assert_lint_err_macro! {
NoUndef,
"({b: a} = {});": [
{
col: 5,
message: "a is not defined",
},
],
"[obj.a, obj.b] = [0, 1];": [
{
col: 1,
message: "obj is not defined",
},
{
col: 8,
message: "obj is not defined",
},
],
"const c = 0; const a = {...b, c};": [
{
col: 27,
message: "b is not defined",
},
],
};
```
In addition to error macro, I also added `assert_lint_ok` macro.
After this PR gets merged, I'll replace `assert_lint_err` and `assert_lint_ok` function with the macro in tests other than `no_unref.rs`.

test: add `assert_lint_err` macro to assert messages and hints 

---

src/rules/no_dupe_keys.rs

What I did In this PR:
- adding more tests (mostly from ESLint)
- allowing it to handle nested objects e.g. `const obj = { a: { b: 1, b: 2 } };`
- adding proper handling for getter and setter with the same name e.g. `const obj = { get a() {}, set a() {} };`

fix(no-dupe-keys): handle nested objects & getter and setter with the same name

---

src/rules/explicit_function_return_type.rs
src/rules/explicit_module_boundary_types.rs
src/rules/for_direction.rs
src/rules/getter_return.rs

This PR contributes to #159, with docs on the following rules:
* explicit-function-return-types
* explicit-module-boundary-types
* for-direction
* getter-return

doc: add lint docs

---

src/rules/no_constant_condition.rs

I was going to fix the false negative that described in #417, but in fact, I fixed it already in #404.
So in this PR, I just added some more tests to make sure `else-if` is handled correctly.
Closes #417

test(no-constant-condition): add tests to make sure else-if is handled

---

src/rules/adjacent_overload_signatures.rs
src/rules/ban_ts_comment.rs
src/rules/ban_types.rs
src/rules/ban_untagged_ignore.rs
src/rules/ban_untagged_todo.rs
src/rules/constructor_super.rs
src/rules/default_param_last.rs
src/rules/eqeqeq.rs
src/rules/explicit_function_return_type.rs
src/rules/explicit_module_boundary_types.rs
src/rules/for_direction.rs
src/rules/getter_return.rs
src/rules/no_array_constructor.rs
src/rules/no_async_promise_executor.rs
src/rules/no_await_in_loop.rs
src/rules/no_case_declarations.rs
src/rules/no_class_assign.rs
src/rules/no_compare_neg_zero.rs
src/rules/no_cond_assign.rs
src/rules/no_const_assign.rs
src/rules/no_constant_condition.rs

This PR:
* Re-orders most examples to put the invalid examples above the valid ones.  This makes more semantic sense ("here's what's wrong followed by here's how it should look"), follows the pattern of eslint and sets a consistent pattern in the deno lint rules.
* Contributes to #159 with documentation now available on the following rules:
* no-class-assign
* no-const-assign
* no-constant-condition

doc: put invalid examples first and add new docs

---

src/rules/constructor_super.rs

This is a part of #431 
Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro and does some refactoring for readability.

refactor(constructor-super): switch to `assert_lint_err!` macro

---

src/rules/ban_untagged_ignore.rs

Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro in `ban-untagged-ignore`.

refactor(ban-untagged-ignore): switch to `assert_lint_err!` macro

---

src/rules/for_direction.rs

Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro in `for-direction`.

refactor(for-direction): switch to `assert_lint_err!` macro

---

src/rules/no_array_constructor.rs
src/rules/no_async_promise_executor.rs
src/rules/no_await_in_loop.rs
src/rules/no_empty_character_class.rs
src/rules/no_empty_pattern.rs
src/rules/no_ex_assign.rs
src/rules/no_explicit_any.rs
src/rules/no_import_assign.rs
src/rules/no_with.rs
src/rules/prefer_namespace_keyword.rs
src/rules/require_yield.rs

Refactored to use `assert_lint_err!` in following rules:
- no-empty-character-class
- no-empty-pattern
- no-ex-assign
- no-explicit-any
- no-import-assign
- require-yield
- prefer-namespace-keyword
- no-with
- no-async-promise-executor
- no-array-constructor
- no-await-in-loop
Ref #431

refactor: use assert_lint_err! macro

---

examples/dlint/main.rs

Sometimes I feel like having the list of all rules. For example, in case where a check box list is wanted just like #431.
So I added a new subcommand `all-rules` to dlint example. This is how it works:

feat(example): add all-rules subcommand

---

src/rules/getter_return.rs
src/swc_util.rs
src/test_util.rs

Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro in `getter-return`. Additionally, fixes some more things.

refactor(getter-return): switch to `assert_lint_err!` macro

---

src/rules/no_case_declarations.rs

Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro in `no-case-declarations`.

refactor(no-case-declarations): switch to `assert_lint_err!` macro

---

src/rules/no_obj_calls.rs
src/rules/no_octal.rs
src/rules/no_prototype_builtins.rs
src/rules/no_redeclare.rs

Part of #431 
Switches from the `assert_lint_err` functions to the `assert_lint_err!` macro:
- `no-obj-calls`
- `no-octal`
- `no-prototype-builtins`
- `no-redeclare`
Hopefully you don't mind me going ahead and completing a few without commenting on the issue. :-)

refactor: assert_lint_err! macro

---

src/rules/no_empty.rs

Fixes #469 
Additionally, switching to `assert_lint_err!` macro is done. #431

fix(no-empty): fix contains_comments logic

---

src/rules/no_explicit_any.rs
src/rules/no_extra_boolean_cast.rs
src/rules/no_extra_non_null_assertion.rs

This PR contributes to #159  with linting hints and docs on the following rules:
* no-explicit-any
* no-extra-boolean-cast
* no-extra-non-null-assertion

doc: add linting hints and docs

---

src/rules/camelcase.rs

Fixes #475 
We are forced to use snake_case keys in object literals in some cases such as an object representing database schema. In such cases, one is allowed to use snake_case by wrapping a key in quotation mark. To tell users this fact, hint message for object keys is fixed.
```typescript
const obj = { "created_at": "2020-10-30T13:16:45+09:00" };
const obj = { "created_at": created_at };
```
```typescript
var o = { bar_baz: 1 };
// the hint looks like:
// Consider renaming `bar_baz` to `barBaz`, or wrapping it in quotation mark like `"bar_baz"`
var o = { bar_baz };
// the hint looks like:
// Consider writing `barBaz: bar_baz` or `"bar_baz": bar_baz`
```

fix(camelcase): fix hint for object keys

---

src/rules/no_fallthrough.rs

Fixes #467 
This seems unideal but I couldn't come up with a better way of handling it.
For snippets like this:
```js
switch(foo) {
case 0:
default:
foo()
```
There seems to be no body detected for `case 0`, to get around this count the new lines. If there's no body and there's more than 1 new line in the span of `case 0:\n\n default:` then the body must be made up of only new lines.
(Thanks for the help bartlomieju)

fix(no-fallthrough): allow no body for statement fallthrough

---

examples/dlint/main.rs
src/control_flow.rs
src/ignore_directives.rs
src/lib.rs
src/linter.rs
src/rules/adjacent_overload_signatures.rs
src/rules/no_inner_declarations.rs
src/rules/prefer_const.rs
src/scopes.rs
src/swc_util.rs
src/test_util.rs

This commit removes "FileType" added in #445. 
This is done by removing "AstParser::parse_script" and "AstParser::parse_module"
in favor of "AstParser::parse_program" which uses new "parse_program"
API provided by SWC.

refactor: use parse_program() for parsing

---

Cargo.lock
Cargo.toml
examples/dlint/main.rs
src/lib.rs
src/linter.rs
src/test_util.rs

This commit changes return type of "Linter::lint" to return
instance of "swc_common::SourceFile" alongside diagnostics. 
It allows to leverage meta data stored by SWC when formatting 
(eg. line indexes).
Fixes https://github.com/denoland/deno_lint/issues/393

refactor: return SourceFile from Linter::lint

---

src/ignore_directives.rs
src/linter.rs

This commit drops support for defining multiple ignore directives,
meaning that it's not possible to ignore diagnostics using eg.
"deno-lint-ignore" and "eslint-ignore-next-line" comments.
Only a single such comment is recongnized.
Additionally fixed matching diagnostic code to use 
strict comparison instead of matching suffix. This imples
that it's not longer possible to ignore using "@eslint-typescript/"
prefix.
Fixes https://github.com/denoland/deno_lint/issues/287
Ref https://github.com/denoland/deno/issues/8226

refactor: drop support for multiple ignore directives and match rule code strictly

---

Cargo.lock
Cargo.toml
src/rules/no_undef.rs

Fixes #463 
Ref: #486 
CC @kdy1 @bartlomieju

fix(no-undef): handle hoisted class declarations

---

examples/dlint/main.rs

This PR adds `--rule` option to `dlint run` commandm, which allows us to run __a certain rule__ only.
It is very useful when developers work on fixing a certain rule's bug. For example, I work on `getter-return` and when I think I've done with it, I want to make sure that there's no regression. Of course we have test cases in `deno_lint` for that purpose, but sometimes it is not enough. So I always run a command like this to see a result:
```sh
ls /path/to/deno/**/*.js -1 | grep -v -e 'node_modules' -e 'target' | xargs cargo run --example dlint -- run 2>&1 | less
```
This command produces so many errors that I cannot confirm there's no regression with my fix.
In this case, if we use `--rule` option, we'll be able to get errors we want to see, which should help find any regression easily.

feat(example): add `--rule` option to dlint

---

src/rules/no_eval.rs

Fixes #466 
Detect `eval` usage in the following situations:
```
this.eval();
var foo = eval;
(0, eval)();
((eval))();
```

fix(no-eval): catch missing eval cases

---

src/rules/no_control_regex.rs

Part of #431 
Additionally replaces `Visit` with `VisitAll` and adds tests for `read_hex_n` and `read_hex_until_brace`.

refactor(no-control-regex): switch to `asset_lint_err!` macro

---

src/rules/no_dupe_args.rs

refactor(no-dupe-args): switch to `asset_lint_err!` macro

---

src/rules/no_dupe_class_members.rs

refactor(no-dupe-class-members): switch to `asset_lint_err!` macro

---

src/rules/no_dupe_keys.rs

refactor(no-dupe-keys): switch to `asset_lint_err!` macro

---

src/rules/no_dupe_else_if.rs
src/swc_util.rs

We have a utility for dropping span from `Expr` in `src/swc_util.rs` and use it in `no-dupe-else-if` implementation.
But as described in https://github.com/denoland/deno_lint/pull/520#discussion_r519424880,  the same utility exists in `swc_ecmascript`. So in this PR, I removed our utility, and delegated it to `swc_ecmascript`.

refactor: delegate DropSpan to swc_ecmascript::utils

---

src/rules/no_extra_non_null_assertion.rs

Part of #431
Additionally replaces Visit with VisitAll

refactor(no-extra-non-null-assertion): switch to `asset_lint_err!` macro

---

src/rules/no_extra_boolean_cast.rs

Part of #431 
Additionally replaces `Visit` with `VisitAll`

refactor(no-extra-boolean-cast): switch to `asset_lint_err!` macro

---

src/rules/no_func_assign.rs
src/scopes.rs

Part of #431, #330
What's done in this PR:
- fix scope analyzer to handle `FnExpr` properly
- handle nested assignments using `VisitAll` trait
- switch to `assert_lint_err!` macro
- port tests from ESLint

fix(no-func-assign): handle FnExpr and nested assignments

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
src/rules/no_dupe_class_members.rs
src/rules/no_dupe_keys.rs
src/swc_util.rs

Thanks to https://github.com/swc-project/swc/pull/1192, BigInt keys can be parsed correctly, which allows us to address a TODO comment in `no-dupe-keys`.
(EDIT) Plus addressed CI issues :)

fix(no-dupe-keys): deal with BigInt keys

---

src/rules/no_global_assign.rs

refactor(no-global-assign): switch to `asset_lint_err!` macro

---

src/rules/no_inferrable_types.rs

~~WIP~~
(EDIT)
Part of #431 and #330 
The current implementation doesn't handle either nested things or multiple variable declarations. In this PR, I addressed those problems by replacing `Visit` with `VisitAll` and fixing `visit_var_decl` implmenetation.

fix(no-inferrable-types): handle nested things properly

---

src/rules/no_inner_declarations.rs

Part of #431 
Additionally, I refactored the following things:
- replace `Vec` with `HashSet` for efficiency
- use `VisitAll` instead of `Visit` in `ValidDeclsVisitor`
- import `swc_ecmascript_ast` items explicitly to be consistent with other rules

refactor(no-inner-declarations): switch to `asset_lint_err!` macro

---

src/rules/no_ex_assign.rs

Part of #330 
Replacing `Visit` with `VisitAll` so that nested cases will be handled correctly.

fix(no-ex-assign): handle nested assignments correctly

---

src/rules/no_irregular_whitespace.rs

refactor(no-irregular-whitespace): switch to `asset_lint_err!` macro

---

examples/dlint/control-flow.js
examples/dlint/js.rs
examples/dlint/plugins/test_plugin3.js
src/control_flow.rs
src/lib.rs
src/linter.rs

PoC
Let's say we have `foo.js` with the following content:
```javascript
function f() {
return 1;
return "f";
}
function g() {
throw new Error();
return "g";
}
```
running `cargo run --example dlint -- run foo.ts --plugin ./examples/dlint/plugins/test_plugin3.js`, then we can see:

feat(plugin): expose ControlFlow to JS

---

src/rules/no_misused_new.rs

refactor(no-misused-new): switch to `asset_lint_err!` macro

---

src/rules/prefer_as_const.rs

Fixes #567 
~~I'll undraft it after some more refinement.~~
Refs:
#431 #330

fix(prefer-as-const): handle `var_decl` that has no `decl`

---

src/rules/getter_return.rs

Just a minor refactoring. Replaces `std::mem::take` with `Option::take`.

refactor(getter-return): replace std::mem::take with Option::take

---

src/rules/no_mixed_spaces_and_tabs.rs

refactor(no-mixed-spaces-and-tabs): switch to `asset_lint_err!` macro

---

Cargo.lock
Cargo.toml
examples/dlint/js.rs

This PR bumps `deno_core` to 0.74.0 and removes our own `FsModuleLoader` so that it will be delegated to `deno_core`.
refs:
- #415 
- https://github.com/denoland/deno/pull/8523

chore: delegate FsModuleLoader to deno_core

---

.github/workflows/ci.yml
README.md
src/ast_parser.rs
src/js_regex/validator.rs

This PR upgrades Rust used in CI to v1.49.0.
Also, clippy has got additional rules, so I dealt with those warnings.

chore: upgrade rust to 1.49.0

---

src/rules/camelcase.rs

Fixes #587, and additionally, lets `camelcase` rule check TypeScript things such as type aliases, interfaces, and so on.

fix(camelcase): don't check ambient declarations + handle TypeScript things

---

src/rules/no_var.rs

This PR contributes to #159 by adding linting docs to `no_var`.
Should I add non-failing tests for `no_var` using `const` and `let` keywords? I'm not sure because `const` and `let` keywords are not even visited by this rules code.

doc: Add docs and tests for no_var

---

src/ast_parser.rs
src/control_flow.rs
src/lib.rs
src/linter.rs
src/rules/prefer_const.rs
src/test_util.rs

This PR adds a new public API `lint_with_ast`. Here's its signature:
```rust
pub fn lint_with_ast(
&mut self,
file_name: String,
ast: &swc_ecmascript::ast::Program,
comments: swc_common::comments::SingleThreadedComments,
source_map: Rc<SourceMap>,
) -> Result<
(Rc<swc_common::SourceFile>, Vec<LintDiagnostic>),
SwcDiagnosticBuffer,
>
```
where `self` is struct of `Linter`.
The proposed API signature in #580 didn't have `comments` and `source_map` as parameters, but it seems they are also required to lint.
I tried to see if it was possible for `comments` to be an immutable reference rather than the value itself, but in vain. Still it works well, though.
Closes #580

feat: add lint_with_ast API

---

examples/dlint/main.rs

fix(dlint): make order of diagnostics output deterministic

---

src/rules/no_shadow_restricted_names.rs

refactor(no-shadow-restricted-names): switch to `assert_lint_err!` macro

---

src/rules/no_self_assign.rs

Part of #431 and #330
- switches to `assert_lint_err!`
- adds hint
- uses `VisitAll` to handle nested assignments properly

refactor(no-self-assign): switch to `asset_lint_err!` macro

---

Cargo.lock
Cargo.toml
src/rules/camelcase.rs
src/rules/explicit_module_boundary_types.rs
src/rules/for_direction.rs
src/rules/no_const_assign.rs
src/rules/no_dupe_args.rs
src/rules/no_import_assign.rs
src/rules/no_redeclare.rs
src/rules/no_self_assign.rs
src/rules/no_shadow_restricted_names.rs
src/rules/no_undef.rs
src/rules/no_unused_vars.rs
src/rules/prefer_as_const.rs
src/rules/prefer_const.rs
src/scopes.rs

This PR upgrades swc_ecmascript to v0.23.1 which has a breaking change on `Ident`.
It consequently resolves #615, so I have added a new test case to make sure deno_lint doesn't complain the following code:
```ts
class T {
#foo(x) {}
#bar(x) {}
}
```

Upgrade swc_ecmascript to 0.23.1

---

src/rules/no_unreachable.rs

This PR:
1. Let's the rule apply on `enum`s.
Enums transform to runtime objects. Therefore, they can be unreachable. 
2. Ignore `module` declarations.
```typescript
throw new Error(); // <-- will throw at runtime
declare module "SomeModule" {
export function fn(): void;
} // <-- types can be imported.
let a = 1; // <-- this is rather unreachable.
```
My bad for not testing it thoroughly in #618

fix(no-unreachable): do not ignore TsEnum. Ignore TsModuleDecl.

---

src/rules/no_undef.rs

fix(no-undef):  Handle bindings of arrow expressions.

---

Cargo.lock
Cargo.toml
src/rules/no_this_alias.rs

Part of #431, #330
- switch to `assert_lint_err!` macro
- replace `Visit` with `VisitAll` to deal with nested cases
- introduce [`if_chain`](https://docs.rs/if_chain/1.0.1/if_chain/) crate so that chained `if` and `if let` won't have redundant indentations. `if_chain!` macro is simple but so useful that even clippy use it.

refactor(no-this-alias): switch to `assert_lint_err!` macro and cleanup

---

src/rules/no_setter_return.rs

Part of #330, #431
This PR does:
- rewrite with dprint_swc_ecma_ast_view
- refine the implementation to avoid false negatives
- add lots of tests (most come from ESLint)

refactor(no-setter-return): refine with ast-view and add sufficient tests

---

src/rules/no_unsafe_finally.rs

Part of #330, #431
- rewrite the implementation with dprint-swc-ecma-ast-view
- add hint message
- refine the implementation so it can properly work for a) if-statements or functions in finally blocks, b) labeled statements
- add/port more tests referring to [ESLint](https://github.com/eslint/eslint/blob/master/tests/lib/rules/no-unsafe-finally.js)

fix(no-unsafe-finally): deal with if-statements or functions in finally blocks, etc.

---

src/rules/no_unsafe_negation.rs

This PR does:
- add doc
- add hint
- switch to `assert_lint_err!` in test
- use dprint_swc_ecma_ast_view
#159
#431
#330

refactor(no-unsafe-negation): add doc & hint, switch to macro in test, etc.

---

src/rules/no_unused_labels.rs

This PR does:
- add doc
- switch to `assert_lint_err!`
- use dprint_swc_ecma_ast_view
#431
#159

refactor(no-unused-labels): switch to `assert_lint_err!` macro and ast-view

---

src/rules/no_with.rs

Adds the documentation for `no-with` rule.
#159

doc(no-with): add doc

---

src/rules.rs
src/rules/no_await_in_loop.rs
src/rules/no_deprecated_deno_api.rs
src/scopes.rs

Resolves #650 
This new lint rule warns the usage of the deprecated APIs in `Deno` namespace, such as:
```ts
new Deno.Buffer();
new Deno["Buffer"];
new Deno[`Buffer`];
Deno.readAll(reader);
Deno["readAll"](reader);
Deno[`readAll`](reader);
Deno.readAllSync(reader);
Deno["readAllSync"](reader);
Deno[`readAllSync`](reader);
Deno.writeAll(writer, data);
Deno["writeAll"](writer, data);
Deno[`writeAll`](writer, data);
Deno.writeAllSync(writer, data);
Deno["writeAllSync"](writer, data);
Deno[`writeAllSync`](writer, data);
```
Unfortunately, the following example isn't warned due to the limitation of scope analyzer:
```ts
function foo () {
const Deno = 42;
}
Deno.readAll(reader);
```
cc @lucacasonato

feat: implement new lint `no-deprecated-deno-api`

---

README.md

chore: fix link to Deno main repo

---

src/rules/no_undef.rs

This adds a regression test for unpacking arrays/objects in function parameters.
Closes #658

test(no-undef): add regression test for unpacking in function parameters

---

Cargo.lock
Cargo.toml
src/handler.rs
src/rules/camelcase.rs
src/rules/no_setter_return.rs

Upgrades swc_* and dprint-swc-ecma-ast-view, and fixes some implementation to pass the type check.

chore: upgrade dependencies

---

src/rules/no_self_assign.rs

#666 issue is probably caused by missing macro parameter.  When added, the rule displays expected messages.

Add missing fmt parameter in use-side of display macro

---

src/rules/no_unused_vars.rs

This patch fixes https://github.com/denoland/deno_lint/issues/667#issuecomment-821856328
~~This branch has been created from the branch of #677. So please merge #677 first.~~
~~The effective diff can be seen [here](https://github.com/magurotuna/deno_lint/compare/magurotuna:ast-view-comments...no-unused-vars/fake-this).~~

fix(no-unused-vars): mark fake function parameter `this` as used

---

README.md
src/js_regex/reader.rs

This PR
- applies clippy suggestions that recommend we use `assert!` instead of `assert_eq!` in comparing with boolean
- updates the rustc version in README.md

chore: apply clippy suggestions

---

src/rules/no_unused_vars.rs

Fixes #687 
In addition, I noticed I wrote a test case in the wrong place in the previous PR (#686), so move it to the right place.

fix(no-unused-vars): temporarily ignore variables that are being declared in `AssignPatProp`

---

Cargo.lock
Cargo.toml
src/handler.rs
src/rules/no_await_in_loop.rs
src/rules/no_deprecated_deno_api.rs
src/rules/no_namespace.rs
src/rules/no_setter_return.rs
src/rules/no_this_before_super.rs
src/rules/no_unsafe_finally.rs

Upgrades `swc` and `dprint-swc-ecma-ast-view` and adjusts to the interface change in `dprint-swc-ecma-ast-view`.

chore: upgrade swc and dprint-swc-ecma-ast-view

---

.github/ISSUE_TEMPLATE/blank_issue.md
.github/ISSUE_TEMPLATE/bug_report.md

This PR adds two GitHub issue templates, "Blank Issue" and "Bug Report".
Issue templates should be really helpful not only for visitors (especially first-time visitors) to easily file issues but also for developers because we will be able to get uniform, sufficient information from a filled-out template, which will allow us to debug and find the cause.

chore: add GitHub issue templates

---

Cargo.lock
Cargo.toml

We are using `Display` macro from `derive_more` crate to easily
implement `std::fmt::Display` trait for each lint's message and hint.
This macro was a bit tricky; even if passed arguments are invalid format,
it _does_ compile, which results in getting unexpected diagnostic outputs.
This is why the issue #666 happened.
However, in `derive_more` v0.99.14, the macro has been refined so it now
rejects arguments in invalid format at compile-time. This is so useful
for us not to make a mistake.
Ref: https://github.com/JelteF/derive_more/pull/160

chore: upgrade `derive_more` to 0.99.14

---

examples/dlint/main.rs

Before, `--version` is shown in the `--help` text, but the output doesn't list a version number.
```
$ dlint --version
dlint 
```
clap can pull the version from `Cargo.toml` [as shown here](https://github.com/clap-rs/clap/blob/master/examples/09_auto_version.rs). With this change, the version is shown as expected.
```
$ dlint --version
dlint 0.5.0
```

fix: show version from Cargo.toml

---

src/rules/ban_ts_comment.rs

Reimpmements `ban-ts-comment` with ast-view. As you can see, almost nothing has changed.

refactor(ban-ts-comment): reimplement with ast-view

---

src/rules/ban_types.rs

Reimplements `ban-types` with ast-view, and adds hints.

refactor(ban-types): reimplement with ast-view

---

Cargo.lock
Cargo.toml
src/rules/no_octal.rs

Fixes https://github.com/denoland/deno/issues/10954 (partially)

chore: upgrade swc to work with large numeric literals

---

src/rules/ban_untagged_todo.rs

Reimplements `ban-untagged-todo` with ast-view. Trivial fix.

refactor(ban-untagged-todo): reimplement with ast-view

---

src/rules/ban_untagged_ignore.rs

Reimplements `ban-untagged-ignore` with ast-view. It's very easy refactoring like #722 :)

refactor(ban-untagged-ignore): reimplement with ast-view

---

.github/workflows/ci.yml

Same as https://github.com/denoland/deno/pull/10826

chore(ci): skip installing gnu-tar because it's already installed

---

src/rules/no_unused_vars.rs

Clippy complains about naming convention: https://github.com/denoland/deno_lint/runs/2865828573
This commit addresses it.
Blocks #715

chore: follow Rust naming convention

---

src/rules/no_namespace.rs

This adds documentation and a hint to `no-namespace` rule.

doc(no-namespace): add doc and hint

---

.github/workflows/ci.yml
Cargo.lock
Cargo.toml
examples/dlint/color.rs
examples/dlint/lexer.rs
examples/dlint/main.rs
examples/dlint/rules.rs
src/rules/no_deprecated_deno_api.rs

This PR adds a feature that each rule documentation is printed to the terminal with syntax highlight. If this turns out to work fine, we'll add it to `deno lint` as well (https://github.com/denoland/deno/issues/8227).
Current screenshot:

feat(dlint): print rule doc with syntax highlighting

---

src/rules/no_new_symbol.rs

This commit adds documentation for the `no-new-symbol` rule and fixes behavior for an edge case where `Symbol` is not built-in one but user-defined.

docs(no-new-symbol): add doc

---

src/rules/no_obj_calls.rs

This commit adds documentation for the `no-obj-calls` rule and fixes behavior for an edge case where target built-in objects are shadowed by users.

docs(no-obj-calls): add doc

---

src/rules/no_prototype_builtins.rs

This commit adds documentation for the `no-prototype-builtins` rule and fixes typo (`propertyIsEnumerable`).

docs(no-prototype-builtins): add doc

---

Cargo.lock
Cargo.toml

Need this for an upcomming change to deno based on a breaking change in swc.

chore: upgrade swc to 0.46

---

src/rules/no_octal.rs

This commit adds documentation for the `no-octal` rule and hint that suggests to use `0o` instead.

docs(no-octal): add doc

---

examples/dlint/main.rs
src/context.rs
src/lib.rs
src/linter.rs
src/rules.rs
src/rules/ban_unknown_rule_code.rs
src/rules/ban_untagged_ignore.rs
src/rules/ban_unused_ignore.rs
src/test_util.rs

This PR contains a breaking change for the public interface on `LinterBuilder`. Currently `ban-unknown-rule-code` and `ban-unused-ignore` can be opted out by a downstream user via `LinterBuilder`, but this PR will always enable both of them. Accordingly, `lint_unknown_rules(bool)` and `lint_unused_ignore_directives(bool)` on the `LinterBuilder` are removed.
In addition, docs for these two rules are added so that we can see them on https://lint.deno.land.

BREAKING: always enable `ban-unknown-rule-code` and `ban-unused-ignore` & add these docs

---

README.md

Since 2016-11-16 c++filt [1] recognizes rust legacy demangling and will supports newer one(v0 name mangling) [2] [3], so it would be better choice.
[1]: https://sourceware.org/binutils/docs/binutils/c_002b_002bfilt.html
[2]: https://github.com/rust-lang/rfcs/pull/2603
[3]: https://sourceware.org/bugzilla/show_bug.cgi?id=27194

Recommend to use c++filt

---

src/rules/ban_ts_comment.rs
src/rules/no_await_in_loop.rs
src/test_util.rs

In this PR, I have added new rules in assert_lint_err macro, to support common messages and hints.
Test done:
1. Pulled latest changes
2. cargo build --all-targets
3. cargo test

refactor: removing redundancy by creating new macro for asserting (#425)

---

src/rules/no_var.rs

This PR adds `no-var` to the recommended set of rules.
`no-var` is currently not in the recommended set simply because ESLint's recommended set doesn't include the rule either. Not really sure why ESLint doesn't, but given that this rule is considered to be always useful when writing TypeScript/JavaScript in modern fashion, we should probably make it "recommended".

feat(no-var): add "recommended" tag to `no-var`

---

src/rules/no_shadow_restricted_names.rs

This PR refactors `no-shadow-restricted-names` so `check_scope` parameter is removed from `check_pat` method, because it seems unnecessary in the current implementation.

refactor(no-shadow-restricted-names): remove unnecessary parameter

---

src/rules/no_import_assign.rs
src/scopes.rs

This PR removes the rule-dedicated scope analyzer from `no-import-assign`, and instead lets it use the common scope analyzer.
Towards #492

refactor(no-import-assign): remove its own scope analyzer

---

src/rules/no_global_assign.rs

This PR removes the rule-dedicated scope analyzer from `no-global-assign`, and instead lets it use the common scope analyzer.
Towards #492

refactor(no-global-assign): remove its own scope analyzer

---

docs/rules/no_window_prefix.md
src/rules.rs
src/rules/no_window_prefix.rs
src/scopes.rs

This PR adds a new lint rule `no-window-prefix` that bans the use of Web APIs via `window` object.
Closes #682

feat: implement new lint `no-window-prefix`

---

Cargo.lock
Cargo.toml

This was previously pinned, but now `deno_doc` was updated to 1.5.4. I also attempted building CLI and no issues bumping this to 1.5.4 (though I wasn't able to run the tests yet because of `deno_doc` changes)

chore: bump regex dependency to 1.5.4

---

tools/scaffold.ts

This PR adds a scaffold script to help us save time when creating a new lint.
Running `./tools/scaffold.ts foo_bar`, we'll get `src/rules/foo_bar.rs` and `docs/rules/foo_bar.md` with boilerplates being pasted in the files respectively.
I'm planning to write up some instructions for those who are interested in contributing to deno_lint on how to implement a new lint rule. I think this scaffold script should be helpful for them.

chore(tools): add scaffold script to create a new lint

---

.github/workflows/ci.yml
tools/scaffold.ts
tools/tests/scaffold_test.ts

This PR fixes the scaffold script so it can handle input lint names with two or more hyphens like `foo-bar-baz` correctly.

fix(tools): handle input with two or more hyphens correctly

---

.github/workflows/ci.yml
tools/scaffold.ts
tools/tests/scaffold_integration_test.ts
tools/tests/scaffold_test.ts

This PR adds an integration test for the scaffold script. Specifically, it checks if the created files pass `cargo check`.
I kind of hesitated to add this because running the script has side effects. But after further thought, actually we should have it in order to keep the files created by the scaffold scripts up-to-date and able to compile.

test(tools): add integration test for scaffold

---

Cargo.lock
Cargo.toml
docs/rules/prefer_ascii.md
examples/dlint/diagnostics.rs
examples/dlint/main.rs
src/rules.rs
src/rules/prefer_ascii.rs

This PR implements a new lint rule `prefer-ascii` that makes sure that the code is composed of only ASCII characters.
Rendered doc: https://github.com/magurotuna/deno_lint/blob/ace535166b4f42a603f9ff5c540d104b4e932647/docs/rules/prefer_ascii.md
In addition, moves `display_diagnostics` function into `diagnostics.rs` and adds test cases. The previous logic of this function didn't take multi-byte characters into account, which has been fixed as well. However, to properly display diagnostic annotations for double-width characters, we still need to wait for my patch to land: https://github.com/rust-lang/annotate-snippets-rs/pull/46
With the current version of annotate-snippets, displayed diagnostics may point to the wrong position if the snippet contains double-width characters, like:
Closes …

feat: implement new lint `prefer-ascii`

---

.github/workflows/ci.yml
tools/tests/scaffold_integration_test.ts

I don't think it's worth it to run the linter on every platform given that there is basically zero platform specific code.
Additionally, closes #841.

chore(ci): only run lint on ubuntu and improve scaffold integration test

---

docs/rules/no_invalid_triple_slash_reference.md
src/rules/no_invalid_triple_slash_reference.rs

This commit allows to use `/// <reference lib="lib" />` in JavaScript files.
Fixes https://github.com/denoland/deno_lint/issues/854

fix: 'no-invalid-triple-slash-referecence' for JavaScript files

---

Cargo.lock
Cargo.toml
src/rules/prefer_ascii.rs

This PR adds a character's unicode code point to hint, and upgrades annotate-snippets to 0.9.1 so that diagnostics point to the right position when the target character is double-width.
Closes #852

feat(prefer-ascii): print character's unicode code point in hint

---

docs/rules/no_extra_semi.md

The invalid and valid samples look identical.
To my best guess the invalid sample might contain a semicolon at an empty line and at { }.
This is tested with a deno.json config file with and without exclude:"no-extra-semi" option.
```
"lint": {
"files": {
"include": ["./"]
},
"rules": {
"tags": ["recommended"],
"exclude": ["no-extra-semi"]
}
},
```

docs: Fix sample code for invalid "no-extra-semi"

---

src/linter.rs
src/rules.rs
src/rules/ban_unknown_rule_code.rs
src/rules/ban_unused_ignore.rs

Closes https://github.com/denoland/deno_lint/issues/847
This commit adds new method to "LintRule" trait called "priority".
The lower the priority the earlier the rule will be run. This value
defaults to 0 and most rules need not change it.

feat: Add LintRule::priority()

---

src/rules/explicit_function_return_type.rs

fix: ignore class setters for explicit-function-return-type rule

---

src/js_regex/mod.rs
src/js_regex/validator.rs
src/rules/no_empty_character_class.rs
src/rules/no_invalid_regexp.rs

Both `no_empty_character_class` and `no_invalid_regexp` should allow regexp with `d` flag.
Closes #985

fix: allow regexp with `d` flag

---

src/rules/ban_types.rs
src/scopes.rs

Basically if you do:
```ts
import { Symbol } from "./something";
const t: Symbol;
```
...it should not be a lint diagnostic.

fix(ban-types): ban types should not flag non-global types

---

src/rules/prefer_primordials.rs

closes #993
i might be missing something, but the message and hint seem pretty general here. should they be more specific, or is this fine?

handle the 'in' operator in prefer-primordials

---

docs/rules/no_top_level_await.md
src/rules.rs
src/rules/no_top_level_await.rs
www/public/docs.json

This lint rule is useful for `dnt` users because top-level-await doesn't work in CommonJS.
Maybe we should enable this rule in `deno_std`.

feat: add `no-top-level-await` rule

---

src/rules/prefer_primordials.rs

Closes https://github.com/denoland/deno_lint/issues/968

fix(prefer-primordials): Force `SafeArrayIterator` to be used in `for-of` statement in deno core

---

src/rules/explicit_module_boundary_types.rs

Param with default values is ignored as it has a type via its assignment
Closes #1018 #1048

fix(explicit-module-boundary-types): ignore assignment patterns

---

www/README.md
www/pages/ignoring-rules.tsx

- The project start command was wrong, since we need to start from root, the `www/` is needed. Maybe we should add a `deno.json`
- The ignoring-rules page didn't have proper markdown formatting, since the css import url was wrong. As a hotfix, I changed to the one used in the index page, which works

fix: Fix markdown css import url and the starting command in README

---

www/README.md
www/pages/ignoring-rules.tsx

Although the cause is not fully understood, Revert because it now returns "500 Internal Server Error"

Revert "fix: Fix markdown css import url and the starting command in README"

---

src/rules/prefer_primordials.rs

Warns authors of Deno's internal runtime JavaScript to avoid using the global `eval` function.
Fixes #1062.

Include  `eval` in prefer-primordials lint

---

src/rules/no_unused_vars.rs

Closes https://github.com/denoland/deno_lint/issues/672
- Cargo Test Passes

fix: use media_type instead of filename to detect jsx

---

www/deps.ts
www/pages/index.tsx

Add darkmode support for the index page (the ignore rules page was handled already).
The diff on github looks worst than what actually changed.
<details>
<summary>Previous</summary>
</details>
Now:

feat: Add styleing for darkmode

---

examples/dlint/diagnostics.rs
examples/dlint/main.rs

closes https://github.com/denoland/deno_lint/issues/1077
Added a --format compact option that outputs like the following

feat: add compact format

---

src/rules/no_self_assign.rs

fix no_self_assign rule, when getter and private class member with same name.
`NoSelfAssignVisitor#are_same_property()` returns false, if the MemberExpr.prop is a pair of `MemberProp::Ident` and `MemberProp::PrivateName`.

fix: no_self_assign - getter and private class member with same name

---

src/rules/no_self_assign.rs

Fixes #1080 
Changed `make` to `made` in message for no-self-assign rule.

fix: no-self-assign rule grammar

---

src/rules/no_namespace.rs

Fixed to use `media_type` to check file type

fix: use `media_type` instead of file_name

---

src/rules/prefer_primordials.rs

Closes #1106
If the array pattern assignment doesn't have a rest pattern, the object pattern assginment is recommended;
otherwise, using a SafeIterator is recommended.

feat(prefer-primordials): Prevent to use array pattern assignments

---

src/rules/ban_types.rs

Add checks for `BigInt` types, as typescript-eslint does.
https://typescript-eslint.io/rules/ban-types/

update(ban-types): add `BigInt` type check

---

www/pages/ignoring-rules.tsx
www/pages/index.tsx

08235828f96e42af56b8656cd6cab67825b9c594 changed the CSS classes to h-screen which Tailwind CSS defines as `heigth: 100vh;`[1], which isn't what we want ... we want `h-full` for 100% height.
This fixes https://lint.deno.land/ from looking like the following when you scroll down:
[1]: https://tailwindcss.com/docs/height

fix: Fix website background color

---

src/rules/prefer_primordials.rs

There are two changes in this PR
Due to my lack of consideration, I had [a lot of false positives](https://github.com/denoland/deno/pull/17715) in getting deno_lint into deno :bow:
And this can be solved by using the primordials Safe constructors (e.g. `SafeMap`); `SafeRegExp` is not in primordials yet, but I am working on getting it in https://github.com/denoland/deno/pull/17592.
This was not considered.

fix(prefer-primordials): Improve getter properties checking

---

.github/workflows/ci.yml
.github/workflows/release.yml

This commit updates CI to use ubuntu-22.04-xl runners as 20.04-xl will get shut down soon.

ci: update ubuntu to 22.04-xl

---

src/rules/prefer_const.rs
src/test_util.rs

This commit prevents panics from happening when scope analysis fails in `prefer-const` rule.
Towards #1145

fix(prefer-const): avoid panic when scope analysis fails

---

src/rules/prefer_primordials.rs

related: https://github.com/denoland/deno/pull/18952

refactor(prefer-primordials): Use `ObjectHasOwn` instead of `ObjectPrototypeHasOwnProperty`

---

tools/format.ts

This commit lets the outputs of external commands spawned in `tools/format.ts` printed out to stdout and stderr so that we can easily figure out what is wrong with formatting.
Without this patch, the following message is shown to us from which we can identify that there is a format issue somewhere, but it's hard to figure out where the issue is.
```
$ ./tools/format.ts --check
rustfmt
deno fmt
error: Uncaught (in promise) Error: Failed: deno fmt --check benchmarks/benchmarks.ts
throw new Error(
^
at file:///Users/yusuktan/Repo/github.com/magurotuna/deno_lint/tools/format.ts:50:9
at eventLoopTick (ext:core/01_core.js:182:11)
```
With this patch, it will become easy to spot the problematic place:
```
$ ./tools/format.ts --check
rustfmt
deno fmt
from …
```

fix(tools): print the outputs of external commands

---

docs/rules/fresh_handler_export.md
src/rules.rs
src/rules/fresh_handler_export.rs
www/static/docs.json

This adds a new lint rule which helps when fresh users accidentally export middlewares under `handlers` instead of `handler`.
See https://github.com/denoland/fresh/issues/1350

feat: add fresh-handler-export rule

---

docs/rules/no_await_in_sync_fn.md
src/rules.rs
src/rules/no_await_in_sync_fn.rs
www/static/docs.json

Noticed in https://github.com/denoland/fresh/pull/1454 that the default v8 warning is a bit meh. This lint rule should provide a better editor experience.

feat: add no-await-in-sync-fn rule

---

docs/rules/no_console_log.md
src/rules.rs
src/rules/no_console_log.rs

The goal of this PR is to address the [this issue](https://github.com/denoland/deno/issues/20187) presented in the main Deno GitHub repository, which proposes the implementation of a `no-console` rule similar to that of [eslint](https://eslint.org/docs/latest/rules/no-console). In order to add such a rule to `deno lint` in the main Deno repository, we need a rule defined in the linter itself.
This PR achieves that goal by adding in a `NoConsoleLog` lint rule that checks whether a `console.log()` statement is in the specified code

feat(rules): add no console log rule

---

src/rules/camelcase.rs

This ignores the camelcase rule for non-declaration object destructuring and named imports when the name has no local alias.
The rationale behind this change is when you are doing these actions, it indicates you have no control over the identifier.
For example:
```ts
// valid
import { op_something } from "something";
const {
op_arraybuffer_was_detached,
op_transfer_arraybuffer,
op_readable_stream_resource_allocate,
op_readable_stream_resource_get_sink,
op_readable_stream_resource_write_error,
op_readable_stream_resource_write_buf,
op_readable_stream_resource_close,
op_readable_stream_resource_await_close,
} = core.ensureFastOps();
// still invalid as this is a declaration
function myFunc({ camel_case }) {}
```

feat(camelcase): allow for non-declaration object destructuring and named import when has no alias

---

src/rules/fresh_server_event_handlers.rs

Files inside an `(_islands)` folder are considered islands too, even if they are inside the `routes` folder.
Fixes https://github.com/denoland/fresh/issues/1726

fix: local islands treated as server components

---

src/rules/prefer_primordials.rs

I removed false positives in the Deno internal TypeScript code

fix(prefer-primordials): Ignore `TsTypeRef`

---

src/rules/explicit_module_boundary_types.rs

fix: improve explicit-module-boundary-types rule

---

docs/rules/no_import_assertions.md
src/rules.rs
src/rules/no_import_assertions.rs
www/static/docs.json

related: https://github.com/denoland/deno/issues/17944

feat: add no-import-assertions rule

---

examples/dlint/main.rs
src/ast_parser.rs
src/context.rs
src/control_flow/analyze_test.rs
src/control_flow/mod.rs
src/lib.rs
src/linter.rs
src/performance_mark.rs
src/test_util.rs

This is just a cleanup in preparation for another plugin system prototype.
With this commit "Linter" is a struct that should be created only once and used
to lint many files, instead of creating a new instance for every single file.
The API was changed to "Linter::lint_file" that accepts a "LintFileOptions".

refactor: Linter, Context and more

---

README.md

Fix missing features flag for build example

docs: fix missing features flag for build example

---

src/rules/no_deprecated_deno_api.rs

fix https://github.com/denoland/deno_lint/issues/1221
The results
```sh
$ ./target/debug/examples/dlint run /Users/skanehira/dev/github.com/skanehira/sandbox/deno/stream/main.ts
no-deprecated-deno-api
× `Deno.readAll` is deprecated and scheduled for removal in Deno 2.0
╭─[/Users/skanehira/dev/github.com/skanehira/sandbox/deno/stream/main.ts:2:7]
2 │ const file = await Deno.open("./main.ts");
3 │ await Deno.readAll(file);
·       ──────┬─────
·             ╰── Use `ReadableStream` from https://deno.land/api?s=ReadableStream and `toArrayBuffer()` from https://deno.land/std/streams/to_array_buffer.ts?s=toArrayBuffer instead
4 │ Deno.iter(file);
╰────
help: https://lint.deno.land/#no-deprecated-deno-api
no-deprecated-deno-api
× `Deno.iter` is deprecated and scheduled for removal in Deno 2.0 …
```

fix: wrong hint for deprecated Deno APIs

---

src/ignore_directives.rs

Hi,
This is my first contribute in deno codebase. I feel nervous and hope it can go well.
This PR is for #1076.
Please check my updates and slowly guide me to the right direction 🙏. Thanks in advance

feat: add explanation for ignore directives

---

src/rules/no_console.rs
src/rules/no_window.rs

Fixes https://github.com/denoland/deno_lint/issues/1232

fix: improve `no-console` and `no-window` rule analysis

---

docs/rules/no_empty_interface.md
src/rules/no_empty_interface.rs
www/static/docs.json

This PR removes linting error for `interface ABC extends XYZ {}` while keeping lint errors for empty interfaces with no extends (`interface ABC {}`).
Fixes #1249

fix: incorrect lint assumptions  for `no-empty-interface`

---

www/routes/rules/[name].tsx

Hi
By following this link users can learn how the rule is implemented, and discover details about corner cases.
Also it eases potential contributions, if something needs to be fixed or improved about the current rule.

feat(www): add link to rule source on GitHub

---

src/rules/no_fallthrough.rs

Fixes #1196
This PR allows:
```ts
switch (number) {
case 1:
// comment
case 2:
doSomething();
}
```
```ts
switch (number) {
case 1:
case 2:
doSomething();
}
```
but does not allow:
```ts
switch (number) {
case 1:
// comment
doSomething();
case 2:
doSomething();
}
```

fix: allow blank lines and comments in cases that do not stop execution

---

README.md

The referenced file was moved in https://github.com/denoland/deno/commit/66424032a2c78c6010c0a1a1b22a26d081166660

docs: fix link in README to deno repository

---

examples/dlint/main.rs

Supported dlint reporting of syntax/parsing errors.
The commit is made to address issue [23437 from deno repo](https://github.com/denoland/deno/issues/23437)
**Code changes**
Added check for `ParsedSource.diagnostics()` and when it's not empty, an object of `ParseDiagnosticsError` holding the vector of `ParseDiagnostic` objects is returned as an `Err` object within `fn run_linter()` in _deno_lint/examples/dlint/main.rs_ file.
PS: The change within this function was preffered over the suggested one in the issue discussion to maintain the types of returned Err in order to keep the same successful flow, since the run_linter function returns AnyError not some specific one like parse_program function, and also it's much simpler (doesn't need to append the ParseDiagnostic single object that …

fix: Make dlint report syntax/parsing errors

---

examples/dlint/main.rs
src/context.rs
src/lib.rs
src/linter.rs
src/test_util.rs

I want to add more options here and I think the builder pattern is harder to ensure everything is setup correctly.

refactor: remove `LinterBuilder`

---

src/context.rs
src/diagnostic.rs

This is so we can link to JSR docs for certain lint rules in the CLI.

feat: ability to provide a custom docs url

---

src/context.rs
src/diagnostic.rs

This allows easily converting slow type diagnostics to LintDiagnostics in the CLI.

feat: add range_description and info to diagnostic

---

examples/dlint/diagnostics.rs
src/context.rs
src/diagnostic.rs
src/linter.rs
src/test_util.rs

No lint rules in deno lint use this atm, but the CLI does.

feat: support diagnostics without ranges

---

Cargo.lock
Cargo.toml
rust-toolchain.toml
src/handler.rs
src/rules/no_compare_neg_zero.rs
src/rules/no_constant_condition.rs
src/rules/no_deprecated_deno_api.rs
src/rules/no_dupe_class_members.rs
src/rules/no_dupe_else_if.rs
src/rules/no_duplicate_case.rs
src/rules/no_import_assign.rs
src/rules/no_inferrable_types.rs
src/rules/no_inner_declarations.rs
src/rules/no_sync_fn_in_async_fn.rs
src/rules/no_undef.rs
src/rules/no_window_prefix.rs
src/rules/require_yield.rs
src/swc_util.rs

https://github.com/denoland/deno_ast/pull/263

perf: upgrade to deno_ast 0.41

---

Cargo.lock
Cargo.toml
docs/rules/no_node_globals.md
src/rules.rs
src/rules/no_node_globals.rs
www/static/docs.json

Lints things like
```ts
const foo = process.env.FOO; // process global
```
With an automated fix to correct the issue
```ts
import process from "node:process";
const foo = process.env.FOO;
```

feat: Add rule disallowing use of NodeJS global objects

---

src/js_regex/mod.rs
src/js_regex/reader.rs
src/js_regex/unicode.rs
src/js_regex/validator.rs

Fixes https://github.com/denoland/deno_lint/issues/1052.
Instead of using a `char` to represent values, just store a `u32`. This way we never construct invalid `char`s, which is UB.

fix: Don't construct invalid `char`s in regex validator

---

docs/rules/no_node_globals.md
src/rules/no_node_globals.rs
www/static/docs.json

Deno 2 will ship with the `process` global being available by default.
See https://github.com/denoland/deno/issues/25679

fix: remove process global check

---

src/rules/prefer_primordials.rs

Fixes #1113
Refs https://github.com/denoland/deno/pull/25040

fix(prefer-primordials): Force to use null `[[Prototype]]` object

---

schemas/rules.v1.json
src/rules/no_process_global.rs
www/static/docs.json

The PR updates the code of the  [`no-process-global`](https://github.com/denoland/deno_lint/blob/main/src/rules/no_process_global.rs) rule to be `no-process-global` instead of `no-process-globals` in order to be consistent as other rules (code and name are the same). Other than confusion, it solves issues like accessing the rule source code in the [website](https://lint.deno.land/rules/no-process-globals) which currently leads to broken page (press on the [Rule source](https://github.com/denoland/deno_lint/blob/main/src/rules/no_process_globals.rs) button in the rule [page](https://lint.deno.land/rules/no-process-globals)).

refactor: adjust rule code for `no-process-global` to ensure consistency

---

README.md

Update readme to hint at running `deno task update-schemas` when adding a new rule

chore: update readme for new rules

---

docs/rules/jsx_props_no_spread_multi.md
schemas/rules.v1.json
src/rules.rs
src/rules/jsx_props_no_spread_multi.rs
www/static/docs.json

Ensure that you're not spreading the same expression more than one time on a JSX node.

feat: add jsx-props-no-spread-multi rule

---

docs/rules/jsx_no_duplicate_props.md
schemas/rules.v1.json
src/rules.rs
src/rules/jsx_no_duplicate_props.rs
www/static/docs.json

Ensure that the same prop is not passed twice to a JSX node. This is typically a mistake.

feat: add jsx-no-duplicate-props rule

---

docs/rules/no_useless_rename.md
schemas/rules.v1.json
src/rules.rs
src/rules/no_useless_rename.rs
www/static/docs.json

Adds a rule for useless renames:
Invalid:
```ts
import { foo as foo } from "foo";
const { foo: foo } = obj;
export { foo as foo };
```
Valid:
```ts
import { foo as bar } from "foo";
const { foo: bar } = obj;
export { foo as bar };
```

feat: add no-useless-rename rule

---

docs/rules/jsx_no_comment_text_nodes.md
schemas/rules.v1.json
src/rules.rs
src/rules/jsx_no_comment_text_nodes.rs
www/static/docs.json

Passing code comments as JSX text nodes is a common mistake. This Lint rule checks if a code comment was accidentally passed as JSX text by checking if it starts with `//` or `/*`.

feat: add jsx-no-comment-text-nodes rule

---

docs/rules/jsx_no_unescaped_entities.md
schemas/rules.v1.json
src/rules.rs
src/rules/jsx_no_unescaped_entities.rs
www/static/docs.json

This rule ensure that you're not accidentally passing entities like `>` as text when you didn't intend to.

feat: add jsx-no-unescaped-entities rule

---

src/rules/jsx_no_danger_with_children.rs

Technically, JSX children aren't empty in cases like this:
```jsx
<div>
</div>
```
Under the hood there is still a single child that contains only whitespace and is typically dropped during rendering.
```jsx
JSXText {
text: "\n   "
}
```
I forgot about that when writing this rule.
Fixes https://github.com/denoland/deno_lint/issues/1398

fix(jsx-no-danger-with-children): account for ignored JSXText nodes

---

src/rules/jsx_curly_braces.rs

The `jsx-curly-braces` rule should not flag string literal expression children when they're at the end of a line and a child is following after it. This is a common pattern to preserve whitespace as HTML whitespace rules would trim it otherwise.
```tsx
// Valid
<div>
foo{" "}
<span />
</div>
```

fix: jsx_curly_braces flagging trailing space expression

---

src/rules/react_rules_of_hooks.rs

This PR fixes a case of rule-of-hooks. Currently the example below doesn't produce lint diagnostics because of the handling of var declaration:
```js
function Foo() {
if (cond) {
const [state, setState] = useState(0);
}
}
```
This PR fixes the above case.

fix(rule-of-hooks): handle var decl with destructuring

---

src/rules/jsx_curly_braces.rs

Don't turn expression into a string when the JSX child would require escaping or it would clash with `jsx-no-unescaped-entities` rule.
Fixes https://github.com/denoland/deno/issues/28225

fix(jsx-curly-braces): ignore values that require escaping

---

src/rules/react_rules_of_hooks.rs

Need to pop conditional on binary expression exits.
Fixes #1426

fix: nullish coalescing operator conditional detection

---

src/rules/ban_types.rs

Maybe a lsp "quick fix" would be nice to add too

fix(ban-types): Use `PropertyKey` type global in hint message

---

README.md

minor fix: the Rust version in the README was outdated, so this pr updates it.

chore: fix rust version on README.md
